### ISSUE TITLE
Minor issue with batch job numbering

### ISSUE THREAD

**Issue by JMM72** [Nandaka/DanbooruDownloader#100]
I've just noticed. Wiht DanbooruDownloader just started:
* If you add a job in Full Batch Mode, the first one is numbered 0.
* If you load a list, the first job is numbered 1 instead.

I'd also like the column to be a tad wider so a 3-digit number would be displayed correctly, since the columns aren't resizable.

**Comment by Nandaka** [comment]
should be fixed on v3.20161122
