### ISSUE TITLE
Unable to download images from gelbooru

### ISSUE THREAD

**Issue by FlatApio** [Nandaka/DanbooruDownloader#101]
Unable to download images from gelbooru

Whenever I try to download any image from gelbooru, there's an error and no image downloads. I've tried both "Main" and "Full Batch" mode. Both fail to download anything. I'm attaching file with stack traces that the application returned (completed with rough translation of messages outputted in my OS' native language). 

[EDIT: I took the liberty of removing this file.]

I guess it's worth nothing that in "Full Batch" mode the "Current page" counter increments abnormally fast, reaching count of 20 in as little as 5 seconds.

I'm using latest version (DanbooruDownloader20161122-beta). I've tried older version of DD (namely DanbooruDownloader20160117) but the issue remains. 

None of this problems happened to me like a month ago. I were successfully downloading images from gelbooru with no issue. I am still able to download images from sites like danbooru, safebooru, rule34.xxx, Sankaku Complex and Konachan with no problem.

Thanks in advance for any help you could provide.

**Comment by Nandaka** [comment]
Looking on the website: ```API temporarily disabled```

**Comment by FlatApio** [comment]
Drats! Guess all we can do is just wait until gelbooru's mods resolve the situation. 

Thanks for the quick answer. :)

**Comment by FlatApio** [comment]
I should've closed this item right after you last answer, sorry.
Also, gelbooru's mods seems to have resolved the issue and the API is available again.
