### ISSUE TITLE
how big is tags.xml ?

### ISSUE THREAD

**Issue by maskkulin** [Nandaka/DanbooruDownloader#104]
I have already over 11k .xml files and I'm not even sure if what I do is right. Should I've ticked merge or do they merge automatically when the download is complete?

**Comment by wopian** [comment]
If you ticked merge they'll all be merged into a single XML file once the tag download process has finished.

**Comment by maskkulin** [comment]
That answered just one of my questions. I am now on 12k .xml files, it's almost 500 MB big. How big is your xml file? I am just curious how much longer it takes till the download is finished. It's rather annoying because I'm getting 429 error every few minutes, hence I can't let it download over night

**Comment by Nandaka** [comment]
I assume you are trying to update the tags xml from sankaku? It is not required anymore for that site, as it doesn't allow direct download of tags.xml using API (I need to parse each page in tags, and it has 15127 pages).

What I do is by parsing tags in the image post specifically for sankaku based on it css class. It has some limitation that the actual tag type cannot be determined correctly until the detail post page is loaded (usually during image download), else it will show based on current tags.xml data.

Before add to download (tags from danbooru's tags.xml) - Main Tab
![image](https://cloud.githubusercontent.com/assets/836867/21585564/7859c596-d0f5-11e6-8805-64f365a60092.png)

After add to download (parsed based on sankaku image post detail) - Download Tab
![image](https://cloud.githubusercontent.com/assets/836867/21585588/c885fabc-d0f5-11e6-985d-cd9c4538730f.png)

Ensure `Use Global Tags.xml` is disabled in Settings Tab.
![image](https://cloud.githubusercontent.com/assets/836867/21585594/f2227b20-d0f5-11e6-9c90-2edb4b69b87b.png)

**Comment by maskkulin** [comment]
Does this also work with batch mode?

**Comment by Nandaka** [comment]
Should be works in batch mode. Please note, the image post tags parsing is only for sankaku.

**Comment by maskkulin** [comment]
wow so I downloaded 13k tags for no reason. You should really include this in your readme.txt
But now everytime I open danbooru downloader it says no tags.xml and wants to download it

**Comment by Nandaka** [comment]
it is still required for other booru 😄 

sankaku is a bit 'special'

**Comment by maskkulin** [comment]
it's not working for me, pls help

`Query: chakku!_tsuiteru!!
System.IO.FileNotFoundException: Cannot load tags.xml
Dateiname: "tags.xml"
   bei DanbooruDownloader3.DAO.DanbooruTagsDao..ctor(String xmlTagFile)
   bei DanbooruDownloader3.DAO.DanbooruTagsDao.get_Instance()
   bei DanbooruDownloader3.Entity.DanbooruProvider.LoadProviderTagCollection()
   bei DanbooruDownloader3.Helper.ParseTags(String p, DanbooruProvider provider)
   bei DanbooruDownloader3.Engine.SankakuComplexParser.Parse(String data, DanbooruSearchParam searchParam)
   bei DanbooruDownloader3.DAO.DanbooruPostDao..ctor(Stream input, DanbooruPostDaoOption option)
   bei DanbooruDownloader3.FormMain.GetBatchImageList(String url, String query, DanbooruBatchJob job)
   bei DanbooruDownloader3.FormMain.DoBatchJob(BindingList`1 batchJob)
2017-01-02 20:36:01,997 INFO  - [DoBatchJob] Downloading list: https://chan.sankakucomplex.com/post/index?tags=chakku!_tsuiteru!!+rating:explicit&page=2
2017-01-02 20:36:03,401 INFO  - [DoBatchJob] No more image.
2017-01-02 20:36:03,433 INFO  - [DoBatchJob] Batch Job #0: Done
`
