### ISSUE TITLE
Is it possible to use DD for downloading specific files?

### ISSUE THREAD

**Issue by JMM72** [Nandaka/DanbooruDownloader#105]
I often delete duplicates and unwanted images after a download, so what I have is not exactly what I downloaded. I recently lost a rather large amount of images, but I have the filenames, hence the post ID of each. So instead of trying to remember the tags I used to download them, and then delete again duplicates and unwanted files, I'm wondering if it's possible to feed DanbooruDownloader a site, a list of post IDs and let it download and rename the images accordingly. Kind of batch download but instead of tag search, using a 'result list' directly.

This is not a feature request since I think it's rather specific, but before banging my head against the wall I'm asking if it's somewhat possible.

**Comment by Nandaka** [comment]
Technically you can use the generated batch job xml and with search query ```id:<image_id>```. 
Not that elegant though.

``` xml
<?xml version="1.0" encoding="utf-8"?>
<ArrayOfDanbooruBatchJob xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <DanbooruBatchJob>
    <Provider>
      <Name>danbooru</Name>
      <DefaultLimit>20</DefaultLimit>
      <HardLimit>1000</HardLimit>
      <Preferred>Xml</Preferred>
      <QueryStringXml>/post/index.xml?%_query%</QueryStringXml>
      <QueryStringJson>/post/index.json?%_query%</QueryStringJson>
      <QueryStringHtml>/post/index?%_query%</QueryStringHtml>
      <Url>http://danbooru.donmai.us</Url>
      <UserName></UserName>
      <Password />
      <LoginType>Cookie</LoginType>
      <PasswordSalt>choujin-steiner--%PASSWORD%--</PasswordSalt>
      <PasswordHash />
      <BoardType>Danbooru</BoardType>
      <TagDownloadUseLoop>true</TagDownloadUseLoop>
      <DateTimeFormat>yyyy-MM-dd HH:mm:ss</DateTimeFormat>
    </Provider>
    <ProviderName>danbooru</ProviderName>
    <SaveFolder>%searchtag%\%provider%\%id% - %rating% - %tags%</SaveFolder>
    <TagQuery>id:1001</TagQuery>
    <Limit>20</Limit>
    <isCompleted>false</isCompleted>
    <isError>false</isError>
    <StartPage>1</StartPage>
  </DanbooruBatchJob>
</ArrayOfDanbooruBatchJob>
```

**Comment by JMM72** [comment]
And slow, but it's an option, thanks for the tip!
