### ISSUE TITLE
danbooru downloader can't cope with apostrophes

### ISSUE THREAD

**Issue by maskkulin** [Nandaka/DanbooruDownloader#106]
When I download this on sankaku channel "md5:246987650aa30ceed9087137fa2bd57d" it comes out like this https://i.imgur.com/S7vzhbk.jpg

please fix this

**Comment by JMM72** [comment]
I download regularly from Danbooru with apostrophes and other symbols (series queen's_blade, artists like homare_(fool's_art) or lin+). No problems, symbols appear correctly. Maybe it has to do with the option 'Replace underscore with space in Tag'.

**Comment by maskkulin** [comment]
I tested it with Gelbooru, there it works. The problem seems to lay on sankaku complex. 
I also noticed some strange behavior with my tags. Look https://puu.sh/tdA0G/cf3f306480.png
As you can see, I downloaded 10 pics of queen's_blade with the copyright tag on first place. 
But only 4 of them are showing the copyright tag, the rest just uses "_" as copyright.
Yes I already unchecked "Use Global Tags.xml"
Admin if you are still alive, please help

**Comment by JMM72** [comment]
Probably he's on holidays, be patient.

**Comment by maskkulin** [comment]
nice, apostrophes are working now :) Sadly my second problem still remains, did you read my comment? Or should I make a new thread?

**Comment by Nandaka** [comment]
you better make new thread, also post the image id for sample (don't use image, so I can copy/paste for testing). Also, is this affecting the batch job or the normal download?
