### ISSUE TITLE
13 bytes trash files from Rule34.paheal

### ISSUE THREAD

**Issue by Romangelo** [Nandaka/DanbooruDownloader#109]
How to deal with this? It seems like the site can detect robots and stop sending the correct pictures.

**Comment by Nandaka** [comment]
working properly in my side. 

Ensure you can open the website from browser.

Also check the '''DanbooruProviderList.xml''' using notepad, the entry for rule34.paheal.net should be like below snippet:

``` xml
  <DanbooruProvider>
    <Name>rule34.paheal.net</Name>
    <DefaultLimit>0</DefaultLimit>
    <HardLimit>0</HardLimit>
    <Preferred>Xml</Preferred>
    <QueryStringXml>/rss/images/%_query%</QueryStringXml>
    <QueryStringJson />
    <QueryStringHtml />
    <Url>http://rule34.paheal.net</Url>
    <UserName>ui-sidebar-hidden=; ui-tnc-agreed=true; ui-image-zoom=full</UserName>
    <Password />
    <LoginType>Cookie</LoginType>
    <PasswordSalt />
    <PasswordHash />
    <!-- Fri, 07 Oct 2016 17:36:59 -0000 -->
    <DateTimeFormat>ddd, dd MMM yyyy HH:mm:ss zzz</DateTimeFormat>
    <BoardType>Shimmie2</BoardType>
    <TagDownloadUseLoop>false</TagDownloadUseLoop>
  </DanbooruProvider>
```

**Comment by Romangelo** [comment]
It works for some images, doesn't work for some. Around 40-50% of the downloaded images are 13 bytes false files.

**Comment by Nandaka** [comment]
what is this 13bytes files? Do you use firewall? Is it the same if you open the pages from website?

can you upload the file here (zip it first).

**Comment by Romangelo** [comment]
Here's a sample of those files. If I follow the link I can see the image on rule34 properly. I don't have any firewall.

https://www.dropbox.com/s/wnylec9v2jlzlkp/badfile.zip?dl=0

**Comment by Nandaka** [comment]
looks like it returning blank html file.

I do get ```A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 85.17.84.201:80``` in the log file.

**Comment by Romangelo** [comment]
So it's a server issue and I just have to wait for them to fix it?

**Comment by Nandaka** [comment]
I think you better notify them.

```http://rule34-data-000.paheal.net``` is not stable.

**Comment by Nandaka** [comment]
possible solution in #109
