### ISSUE TITLE
Sankakucomplex can't download after page 50

### ISSUE THREAD

**Issue by ashllay** [Nandaka/DanbooruDownloader#111]
log
[DoBatchJob] Downloading list: https://chan.sankakucomplex.com/post/index?tags=nier:_automata&page=51&login=heyned&password_hash="my hash"
[DoBatchJob] Error Getting List (1 of 5): The remote server returned an error: (404) Not Found. Wait for 60s.

looks like sankaku have changed something now after page 50 the link chage 
page 50: /?tags=nier%3A_automata&page=50
page 51: /?next=5783805&tags=nier%3A_automata&page=51

**Comment by Nandaka** [comment]
you can change modify the DanbooruProvider.xml for sankaku as below:

```xml
  <DanbooruProvider>
    <Name>Sankaku Complex (HTTPS)</Name>
    <DefaultLimit>20</DefaultLimit>
    <HardLimit>1000</HardLimit>
    <Preferred>Html</Preferred>
    <QueryStringXml />
    <QueryStringJson />
    <QueryStringHtml>/?%_query%</QueryStringHtml>
    <Url>https://chan.sankakucomplex.com</Url>
    <UserName>login=required; pass_hash=required</UserName>
    <Password />
    <LoginType>Cookie</LoginType>
    <PasswordSalt>choujin-steiner--%PASSWORD%--</PasswordSalt>
    <PasswordHash />
    <!-- 2016-10-07 12:06 -->
    <DateTimeFormat>yyyy-MM-dd HH:mm</DateTimeFormat>
    <BoardType>Danbooru</BoardType>
    <TagDownloadUseLoop>true</TagDownloadUseLoop>
  </DanbooruProvider>
```

and maybe update the user-agent to follow what your browser use?

**Comment by pwner151** [comment]
That didn't fix it for me.

Using RWBY as an example.

https://chan.sankakucomplex.com/?tags=rwby&page=50 You can view up to this point with changing the page# in the url up to 50. Changing it to 51 or above throws the error "Error: You can only view up to 50 pages of results this way".

If you go to page 50 and hit the next page button, the url changes to https://chan.sankakucomplex.com/?next=5691118&tags=rwby&page=51

It looks like they are using the first image that applies to that tag on the next page as the next=#.

Hopefully this helps!

**Comment by Nandaka** [comment]
```Error: You can only view up to 50 pages of results this way```

key in your cookie for sankaku, that message because the session is not authenticated.

**Comment by Nandaka** [comment]
![image](https://cloud.githubusercontent.com/assets/836867/23341534/55753014-fc84-11e6-8d4a-9aa71532104e.png)

**Comment by pwner151** [comment]
Could you explain "key in your cookie for sankaku, that message because the session is not authenticated."? I don't follow your phrasing and google isn't being helpful.

**Comment by Nandaka** [comment]
from readme:
```
Q7: How to login to Gelbooru/Sankaku/get cookie value?
A7: Follow this step:
    1. Press F12 on your Chrome browser and select Network tab.
    2. Go to the booru site and login.
    3. Click one of the entry and copy the Cookie value from the Request Header. 
       For gelbooru, it should like this: user_id=<number>; pass_hash=<long string>
       For sankaku, login=<username>; pass_hash=<long string>;
    4. Paste the Cookie value to the Username field.
    5. Set Login Type to Cookie. Refer to http://i.imgur.com/rCCjnPs.png
```

**Comment by pwner151** [comment]
Ahh, I did that. it didn't fix the issue, though.
Also, as a side question, would it be "login=NAME; pass_hash=Hash" or "login=NAME pass_hash=Hash"?

I don't know how you managed to view page 51 without it .

If I type page 51 into the URL, I get this.
![51 in url](https://cloud.githubusercontent.com/assets/26043195/23367245/8e1e1e96-fcd7-11e6-9b3d-0b903c8ec71f.png)
If I type 50, then hit the next page icon, I get this.
![51 via next](https://cloud.githubusercontent.com/assets/26043195/23367273/a967213e-fcd7-11e6-9e79-bfe3a0ec0495.png)

I believe this is the same issue ashllay is having. The parser (is this the right term?) can't manually go from 50 to 51 (without tricks), since Sankaku seems to have changed their backend to discourage this kind of thing.

Hopefully I'm helping with relevant information to this issue. x.x

**Comment by Nandaka** [comment]
use ```;``` to separate the field. I just copy and paste the whole cookie values to the provider xml though.

![image](https://cloud.githubusercontent.com/assets/836867/23402215/9b60fbaa-fde5-11e6-91a1-f0d497b0cb30.png)

notice that it also have ```mode=view; auto_page=1;``` in the cookie, maybe this is why?

I'll check it if the application can get the next url

**Comment by pwner151** [comment]
None of this is fixing the problem that I've been having, sadly. :/

Would it be better for me to send you my personal "installation", zipped? It'll also have my SC login, so you can see whats wrong there? (It might be that I haven't contributed to the site or something)

**Comment by tikkariz** [comment]
I have same problem with pwner151, and have had this for while (over 4 months).
Tried do things what Nandaka said in this thread, but they are not working for me, it still gets stuck in page 51.
http://i.imgur.com/B7XjjU1.png
http://i.imgur.com/xcIx1YF.png
Even donwloaded lastest fresh version, but nothing, hope something can be done

**Comment by Wassaaaa** [comment]
I'm having problems too trying to download after page 50, is there a way to provide an username and password without the cookie option?

**Comment by rexii2300** [comment]
same issue here. Using cookie method doesn't help either

**Comment by Kicos** [comment]
i dont know if it matters, but there is a change in the url from page 50 to 51.

chan.sankakucomplex.com/?tags=touhou%20yuri&page=50

chan.sankakucomplex.com/?**next=5356938&**tags=touhou%20yuri&page=51

**Comment by jasonmbrown** [comment]
Im also still encountering this error. Including when i attempt to load any page past 50 in my Browser, Unless Autopaging is turned off, and I goto page 50 then click next page.

Browser and Downloader are both logged in.

**Comment by Nandaka** [comment]
Looks like I need to pass the last post id as part of the ```next``` parameter.

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/DanbooruDownloader/releases/tag/v3.20170922
