### ISSUE TITLE
Blacklisted tags aren't ignored?

### ISSUE THREAD

**Issue by radixwolf** [Nandaka/DanbooruDownloader#112]
From what I see, the program says it should ignore the tags that are put into the "Blacklisted Tags" box, but it still allows me to select it when clicking select all. I thought it was supposed to select all but ignore the blacklisted tagged images? 

Is there a way for me to un-select JUST the images with tags that I have on my blacklist?

**Comment by Nandaka** [comment]
currently nope, as blacklisting is more used in batch download.

If you always use 'select all' button, why not use the batch download feature?

**Comment by radixwolf** [comment]
I must not be familiar with the batch download feature. How would I use the full batch mode to download images and exclude the download of blacklisted tagged images?

**Comment by Nandaka** [comment]
it should be automatic if you have some blacklisted tag configured.

**Comment by radixwolf** [comment]
When using Full Batch Mode, no, blacklisted images are still downloaded even though I have the tags blacklisted.

**Comment by Nandaka** [comment]
can you upload the log file and your settings tab screenshot?

It should shows something like below in the log (e.g. blacklisted yaoi):
```
[DoBatchJob] Download skipped, contains blacklisted tag: 2boys armin_arlert bespectacled black_hair black_panties blonde_hair blue_eyes blue_skirt bulge character_request cosplay crossdressing elbow_gloves eren_yeager glasses gloves highleg highleg_panties kantai_collection looking_at_viewer male_focus marimo_danshaku midriff mirror multiple_boys navel open_mouth otoko_no_ko panties semi-rimless_glasses shimakaze_(kantai_collection) shimakaze_(kantai_collection)_(cosplay) shingeki_no_kyojin skirt solo_focus striped striped_legwear thighhighs under-rim_glasses underwear yaoi Url: http://danbooru.donmai.us/data/__armin_arlert_eren_yeager_and_shimakaze_kantai_collection_and_shingeki_no_kyojin_drawn_by_marimo_danshaku__372cdf3b9ae3621b7e2f1b5b9cbded05.jpg
[DoBatchJob] Download skipped, contains blacklisted tag: 2boys ag_ss41 armor blush carrying_over_shoulder dark_skin fate/apocrypha fate_(series) fur_collar karna_(fate) kiss long_hair male_focus multiple_boys pale_skin saber_of_black short_hair white_hair yaoi younger Url: http://danbooru.donmai.us/data/__karna_and_saber_of_black_fate_apocrypha_and_fate_series_drawn_by_ag_ss41__47583c5cd8795fe6809dd7ac63498557.jpg
```
