### ISSUE TITLE
Tags Downloading for Sankaku (Https)

### ISSUE THREAD

**Issue by Aaeeschylus** [Nandaka/DanbooruDownloader#119]
So i was downloading the tags from sankaku (https). I finished all the downloads... all 15522 pages of it. It took a while and now there are heaps of .!tmp files, one for each page. The tag downloading window now say "status: merging page 1. This may take some time." It has been like this for 3 hours now. Can anyone offer some assistance? Im not sure if I can close it now or not and start downloading from sankaku.

**Comment by Aaeeschylus** [comment]
if it helps, i clicked the download button again and it skipped through all the downloads cause all the tmp files are there. however this time i got an error that i did not see last time. I have put it here: https://pastebin.com/i8bNLfBn

**Comment by JMM72** [comment]
Merging 15000 pages could really take all that time, depending on how the merging is implemented. Do it late at night and leave it running during the night to see what happens. Delete all tmp files too, that error shows that it chokes on the tmp files.

**Comment by Aaeeschylus** [comment]
ive had it running for 2 days, it stays on merging file 1... i think the error has something to do with it

**Comment by JMM72** [comment]
Yes, if it doesn't move from file 1, then something wrong is happening. Even slowly, it should advance. Something unexpected must be in file 1 that doesn't allow DD to advance. Be patient and let Nandaka come and see what happens.

**Comment by maskkulin** [comment]
https://github.com/Nandaka/DanbooruDownloader/issues/104
you don't even have to download tags for sankakucomplex. I told him he should  include this in the readme.txt of course he didn't do it. Still it never really worked for me, I highly recommend this program instead: https://github.com/Bionus/imgbrd-grabber
there you don't need to download tags

**Comment by JMM72** [comment]
Well, you don't have to download tags for anything, unless you want to use %artist% and other renaming facilities. Once you have a tags.xml e.g. from Danbooru or Yande.re you don't need to download tags from any other board.

**Comment by GiRaFa-SM** [comment]
OP see: https://github.com/Nandaka/DanbooruDownloader/issues/126
