### ISSUE TITLE
3dBooru no longer working the way it used to.

### ISSUE THREAD

**Issue by ghost** [Nandaka/DanbooruDownloader#123]
Not sure what has changed but when downloanding from behoimi.org the photo sets no longer get put in a separate directory. I used to use the save string of %searchtag%\%faults%\%id% but that no longer works did the booru change something or is it something I've missed?

This is what it looks like from the log
`[DoBatchJob] Downloading list: http://behoimi.org/post/index.xml?tags=tachibana_sari&limit=100&page=1
[DoBatchJob] Download: http://behoimi.org/data/0c/00/0c00a6e25a6d6c227e4cd09bc42d81f1.jpg
[DoBatchJob] Saved To: E:\boorubooru\----====Photo sets====----\tachibana_sari\\636693.jpg
[DoBatchJob] Download: http://behoimi.org/data/24/42/244225c4f2a7a1b2f10ad78f3137cebb.jpg
[DoBatchJob] Saved To: E:\boorubooru\----====Photo sets====----\tachibana_sari\\636692.jpg
[DoBatchJob] Download: http://behoimi.org/data/a6/85/a685d115d6bd589d90e342668444d8cb.jpg
[DoBatchJob] Saved To: E:\boorubooru\----====Photo sets====----\tachibana_sari\\636691.jpg
[DoBatchJob] Download: http://behoimi.org/data/8e/ed/8eed2a48df20ec94972a51feeb5fa061.jpg
[DoBatchJob] Saved To: E:\boorubooru\----====Photo sets====----\tachibana_sari\\636690.jpg
[DoBatchJob] Download: http://behoimi.org/data/c0/1f/c01f2af12cc520cd29765806eda5e264.jpg
[DoBatchJob] Saved To: E:\boorubooru\----====Photo sets====----\tachibana_sari\\636689.jpg
[DoBatchJob] Download: http://behoimi.org/data/2c/9e/2c9ee9de54627fbd6e561937c35b0a7a.jpg
[DoBatchJob] Saved To: E:\boorubooru\----====Photo sets====----\tachibana_sari\\636688.jpg
[DoBatchJob] Download: http://behoimi.org/data/85/ae/85aeece457d518ae5934e62d157ce74e.jpg
[DoBatchJob] Saved To: E:\boorubooru\----====Photo sets====----\tachibana_sari\\636687.jpg`

**Comment by Nandaka** [comment]
Try to update the tags.xml specific to behoimi? unless the photoset is stored in %faults% category, it looks like it is working as expected.
