### ISSUE TITLE
rule34hentai gow to set up login cookie?

### ISSUE THREAD

**Issue by lollos73** [Nandaka/DanbooruDownloader#124]
hi all i read some post but i don't have idea how to setup full download fo site, i chose cockie, and past on login field somethig like this: "shm_user=xxxxx; shm_session=xxxxxxxLots of letter numberxxxx; Max-Age=" but i hve always error windows can you help me?

**Comment by Nandaka** [comment]
What is the error?

Another option is use a text editor to key in the cookie value.
1. Close the application first, then open ```DanbooruProviderList.xml``` using notepad or your choice of text editor.
2. Go to the *booru sites and get the cookie value (e.g. refer to readme).
3. Paste it to the ```UserName``` section, and set ```LoginType``` to ```Cookie```. Refer to image below.
![image](https://user-images.githubusercontent.com/836867/28102270-c1f252ee-6700-11e7-90f7-fafd3533f8a2.png)
4. Save it and start the application again.
