### ISSUE TITLE
Hanging prior to downloading new image (danbooru)

### ISSUE THREAD

**Issue by KarasLegion** [Nandaka/DanbooruDownloader#125]
I never experienced this issue on my previous computer which had a Windows 7 installation. This one has a Windows 10 installation, and I'm using the latest DanbooruDownloader iteration.

It hangs just prior to each image it downloads. The downloads themselves are almost instantaneous based on the image size, but then when it goes to start the next it just hangs for a moment. This has greatly slowed down my downloading.

Doesn't happen when I'm using Gelbooru, which I only did as a test, I usually only use Danbooru. Should this be happening?

Edit: I think it's when the list is on the bigger side. Though the fact remains, I usually just run through order:rank which tends to be under 2k. Still never had this issue till now. When I reduce the list size, it doesn't hang anymore, but if I go back to the original size that I usually do it hangs between each.

**Comment by Nandaka** [comment]
can you give me the sample query?
