### ISSUE TITLE
Can't download more then 500 pics.

### ISSUE THREAD

**Issue by Fanservicefan** [Nandaka/DanbooruDownloader#129]
Might be an issue on Sankaku's end. The batch download can only get 498 until it just stops, complete with error red. Why? Happens no matter what tag I use.

**Comment by Nandaka** [comment]
You need to provide the login information to the program, refer to:
```
Q7: How to login to Gelbooru/Sankaku/get cookie value?
A7: Follow this step:
    1. Press F12 on your Chrome browser and select Network tab.
    2. Go to the booru site and login.
    3. Click one of the entry and copy the Cookie value from the Request Header. 
       For gelbooru, it should like this: user_id=<number>; pass_hash=<long string>
       For sankaku, login=<username>; pass_hash=<long string>;
    4. Paste the Cookie value to the Username field.
    5. Set Login Type to Cookie. Refer to http://i.imgur.com/rCCjnPs.png
```

**Comment by Nandaka** [comment]
![image](https://user-images.githubusercontent.com/836867/30521481-be1392f6-9bf2-11e7-8999-fefd17ecdcb4.png)

**Comment by Fanservicefan** [comment]
Do I absolutely NEED Chrome? How can I do this on Firefox?

**Comment by GiRaFa-SM** [comment]
There's no "pass hash" or "login" values on my setcookie, should i copy it?

**Comment by Nandaka** [comment]
Try to check the request header if not exist.
![image](https://user-images.githubusercontent.com/836867/30522692-df38a412-9c06-11e7-96a2-dede0f8459d4.png)

You can use notepad to edit ```DanbooruProviderList.xml``` and paste the whole cookie value to the username section.
![image](https://user-images.githubusercontent.com/836867/30522718-2b26406e-9c07-11e7-91f6-4bb6d5aad0ce.png)

**Comment by GiRaFa-SM** [comment]
Looks like the method 2 is working here, thank you.
