### ISSUE TITLE
Danbooru private images

### ISSUE THREAD

**Issue by Liandriz** [Nandaka/DanbooruDownloader#130]
Hi, more and more posts on Danbooru return some "You need a gold account to see this image." text, so DanbooruDownlader get error on them, and stop the batch, is there any way to just ignore them and continue?

**Comment by CuddleBear92** [comment]
having batch searches that doesnt have the restricted content in them will help. adding -loli or -shota will help as that is the sort of content you need an gold account for. @Liandriz
