### ISSUE TITLE
Danbooru time out

### ISSUE THREAD

**Issue by Romangelo** [Nandaka/DanbooruDownloader#131]
[DoBatchJob] Error Getting List (1 of 5): The remote server returned an error: (500) Internal Server Error. Wait for 60s.
[DoBatchJob] Retrying...
[DoBatchJob] Error Getting List (2 of 5): The remote server returned an error: (500) Internal Server Error. Wait for 60s.
[DoBatchJob] Retrying...
[DoBatchJob] Error Getting List (3 of 5): The remote server returned an error: (500) Internal Server Error. Wait for 60s.
[DoBatchJob] Retrying...
[DoBatchJob] Error Getting List (4 of 5): The remote server returned an error: (500) Internal Server Error. Wait for 60s.
[DoBatchJob] Retrying...
[DoBatchJob] Error Getting List (5 of 5): The remote server returned an error: (500) Internal Server Error. Wait for 60s.
[DoBatchJob] Retrying...
[DoBatchJob] Cannot load list
[DoBatchJob] Batch Job #0: Done

Version 20170808

**Comment by Nandaka** [comment]
Can you open the site?

**Comment by Romangelo** [comment]
I can access the site.

**Comment by Nandaka** [comment]
what is the search query you are using? Danbooru only limit up to 2 keyword for free user.

**Comment by Romangelo** [comment]
only one keyword that is the name of a series.

**Comment by Romangelo** [comment]
Sometimes it can download the first page (200 pics) and then "no more image" for the next page.

[DoBatchJob] Downloading list: http://danbooru.donmai.us/post/index.xml?tags=suzumiya_haruhi_no_yuuutsu&limit=1000&page=2
[DoBatchJob] No more image.
[DoBatchJob] Batch Job #0: Done

**Comment by Nandaka** [comment]
I think they changed the limit to max = 100? I tired to open the url and it give me error.
![image](https://user-images.githubusercontent.com/836867/30072067-c16822ba-929b-11e7-8f14-22843edc5b1b.png)
