### ISSUE TITLE
Sankaku gives fake image files

### ISSUE THREAD

**Issue by Romangelo** [Nandaka/DanbooruDownloader#133]
I think it began yesterday. All the images downloaded from this site are a placeholder file.

**Comment by matsumotokenji** [comment]
Same thing here just happened few hours ago.
![expired](https://user-images.githubusercontent.com/22205034/30036081-9e8e976a-91e2-11e7-932d-6e6318fff0f8.png)

**Comment by Deejay85** [comment]
This has been going on for about three days now. I tried a new tag since it first occurred using the date token, but that didn't fix it.

**Comment by NIK220V** [comment]
That's because of Sankaku's new token system for images.
No ideas on how this could be fixed, since they all are unique.
Still, getting a working link is possible, if parsing the post page, not the search page.

**Comment by Nandaka** [comment]
I do parse the individual post image to get the actual url, I got issue need to decode the ampersand.

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/DanbooruDownloader/releases/tag/v3.20170906
