### ISSUE TITLE
Sankaku error : Expired Link - Please reload the site

### ISSUE THREAD

**Issue by Lacarotte** [Nandaka/DanbooruDownloader#134]
Hi, I have an issue when downloading batch from chan.sankaku. It load the pages download the pictures with the correct mane but not the picture related. It only download the same error pic : a 392x200 14.4ko pic with the message "Expired Link - Please reload the site"

How do I fix this ? thx

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/DanbooruDownloader/releases/tag/v3.20170906

**Comment by Lacarotte** [comment]
It works ! Thx for the fix <3

**Comment by matsumotokenji** [comment]
run through a list of artist, for https://chan.sankakucomplex.com/?tags= some artist show no result in v3.20170906 but ok in chrome browser for me (e.g. anyannko !!!NOTE: NSFW AND NOT SAFE HEN-TIE!!!) and others ok but sometimes will come out "Expired Link - Please reload the site" randomly (2 occurance, can't seem to duplicate, maybe try Main Search in danbooru then batch download at sankakucomplex?).
