### ISSUE TITLE
How to log in SankakuComplex?

### ISSUE THREAD

**Issue by GiRaFa-SM** [Nandaka/DanbooruDownloader#136]
I cant download/see more than 500 pics/pages(29) through DD, how i can log into my acc through DD? Is there any risk of ban by doing this?

**Comment by GiRaFa-SM** [comment]
I think this issue is related with this one : https://github.com/Nandaka/DanbooruDownloader/issues/129 but i cant figure out how to extract the necessary info on chrome, can someone help me? I cant find the login tag.

**Comment by Nandaka** [comment]
I'll close this issue and continue it to original thread #129
