### ISSUE TITLE
attempting to batch download from gelbooru results in an error

### ISSUE THREAD

**Issue by goldnharl** [Nandaka/DanbooruDownloader#138]
when I attempt to download from gelbooru using the batch downloader, it skips over any files and does not register any file under any tag. frankly, this program is confusing for me, so i'm almost positive i'm doing something wrong. i can and have downloaded images from rule34hentai using the batch downloader, but any attempts to download gelbooru images in batch, or with the main tab, where no thumbnails or previews even appear, fail. thanks for any help. i'd really like to get this working, but i think i'm just confused by how it works exactly.

**Comment by Nandaka** [comment]
Weird, I can download just fine. Ensure you can open the website in the browser.

For the thumbnail, ensure ```Load Preview``` check box is tick.
![image](https://user-images.githubusercontent.com/836867/31061940-8db31a5c-a758-11e7-8999-81725bb6be9a.png)
![image](https://user-images.githubusercontent.com/836867/31061963-0359c2c4-a759-11e7-8a05-64cb7c2fdc45.png)

Also, can you upload the log file (e.g. ```log-2017-10-02.txt```)?

**Comment by goldnharl** [comment]
sure, here: https://pastebin.com/Wiir9Z2M

I can access gelbooru easily, and search up the terms. I have tried it today, just now, and the log tab displayed this:

[clientList]I:\Documents and Settings\Aslan Vondran\Desktop\DanbooruDownloader20170922\gelbooru.com - 3d animated .xml    downloaded 3248 of -1 bytes. 0 % complete...
[clientList]I:\Documents and Settings\Aslan Vondran\Desktop\DanbooruDownloader20170922\gelbooru.com - 3d animated .xml    downloaded 3248 of 3248 bytes. 100 % complete...
[clientList_DownloadFileCompleted] Download Complete: I:\Documents and Settings\Aslan Vondran\Desktop\DanbooruDownloader20170922\gelbooru.com - 3d animated .xml

No files were downloaded and no thumbnails displayed. Like I said, I really think this is just me being an idiot, but I'm at a loss.

**Comment by Nandaka** [comment]
Try to delete ```tags.xml.1.!tmp``` files from the application folder?

**Comment by goldnharl** [comment]
thanks! that seems to have fixed everything.
