### ISSUE TITLE
problem with rule34hentai.net

### ISSUE THREAD

**Issue by lee27** [Nandaka/DanbooruDownloader#140]
Hello to everyone I have a problem, I'm trying to download, using full batch mode, a random tag with only four images, but why when i start downloading, download two and the other two remain skipped?

**Comment by Nandaka** [comment]
Can you upload the log file here? It should be something like ```log-2017-10-06.txt``` in the application folder.

**Comment by Nandaka** [comment]
No error inside. The last few entries stated that the file is skipped because it is already exists.

```2017-10-08 12:56:50,214 INFO  - [DoBatchJob] Download skipped, file exists: L:\PROGRAMMI\DanbooruDownloader-master\Download\danbooru\s - ryoji_(nomura_ryouji) - Multiple Character - little_princess marl_kingdom rhapsody - 1boy.jpg```

Can you tell me what is the tags you are using so I can replicate it?

**Comment by lee27** [comment]
tags I use are these, the images are different, however, they recognize them as the same, will have the same tag

**Comment by Nandaka** [comment]
Then it is working as expected, as it only check whether the file name already exists or not (else the old file will be overwritten).

Add %id% to make it unique.

**Comment by lee27** [comment]
GREAT! Work! Thank you!!!

**Comment by lee27** [comment]
sorry, new problem, i am trying to download another tag but the download stops at 10 images, there should be many more pictures

**Comment by Nandaka** [comment]
Do you set the limit?
![image](https://user-images.githubusercontent.com/836867/31396620-7b7b0a7e-ae16-11e7-9e4d-659fea6a1c89.png)

else give me more information, else I cannot check the issue.

**Comment by lee27** [comment]
LIMIT 9999 START PAGE 1 TAG QUERY = the_last_of_us PROVIDER rule34hentai.net

**Comment by Nandaka** [comment]
Weird, I can download more than 10. Can you retry and upload the new log file?
![image](https://user-images.githubusercontent.com/836867/31415631-243270d6-ae57-11e7-8bb0-6be962028019.png)

**Comment by lee27** [comment]
[log-2017-10-10.txt](https://github.com/Nandaka/DanbooruDownloader/files/1374543/log-2017-10-10.txt)

**Comment by Nandaka** [comment]
can you download the latest release from https://github.com/Nandaka/DanbooruDownloader/releases

I notice you still using ```3.2017.08.08```

**Comment by lee27** [comment]
now it downloads more pictures, but not all, there are many more

**Comment by Nandaka** [comment]
Can you open ```http://rule34hentai.net/index.php?q=/rss/images/the_last_of_us/7``` and see whether it return any images? The apps used the API to fetch the image list.

**Comment by lee27** [comment]
I can not see the picture

**Comment by Nandaka** [comment]
yep, same here. The server didn't return any images. 

The server only return 6 pages of images using that API.

**Comment by lee27** [comment]
then? do not download all images for this issue? what should I do?

**Comment by Nandaka** [comment]
you need to ask them (rule34hentai.net) to check why RSS API url (http://rule34hentai.net/index.php?q=/rss/images/) return different data with the normal pages? This one I cannot help. I won't do specific site page scraping if there is API available.

**Comment by lee27** [comment]
ok, let me know, thank you very much for everything if you were really kind
