### ISSUE TITLE
danbooru downloader not checking MD5 Hash only checking filenames

### ISSUE THREAD

**Issue by rushuna86** [Nandaka/DanbooruDownloader#141]
not sure if i have some setting wrong or not...but if i download %originalFilename% and then decided to change it to something else eg. %ID%_blah blah and re download the same tags again. It doesnt actually check the md5 hash. Only checks if filename exist...and because it's a different filename format it redownloads the same image again.

**Comment by Nandaka** [comment]
it doesn't and won't check the md5. It only check if the filename exists or not.

The MD5 is given from server and not used for checking.

**Comment by rushuna86** [comment]
anyway to implement a check? i know 1 of the other grabbers writes the file name and the md5 for it into a table and checks against that. useful for downloading across multiple sites who have different naming structures.

**Comment by Nandaka** [comment]
nope, it doesn't have db to write and I don't plan to add that feature.

**Comment by rushuna86** [comment]
how about wildcard name check? *_%md5%?

**Comment by Nandaka** [comment]
nope, it will became an issue if the downloaded file is not at the same folder (e.g. using provider/search keyword name as folder).

It is easier for me to use duplicate finder and delete the duplicated ones.

**Comment by rushuna86** [comment]
ohhh okay thanks :D
