### ISSUE TITLE
problem with gelbooru

### ISSUE THREAD

**Issue by lee27** [Nandaka/DanbooruDownloader#142]
hello to everyone, using fullbatch mode with danbooru downloader set gelbooru as provider, i do not find any picture, why?

**Comment by Nandaka** [comment]
check the readme

```Q7: How to login to Gelbooru/Sankaku/get cookie value?
A7: Follow this step:
    1. Press F12 on your Chrome browser and select Network tab.
    2. Go to the booru site and login.
    3. Click one of the entry and copy the Cookie value from the Request Header. 
       For gelbooru, it should like this: user_id=<number>; pass_hash=<long string>
       For sankaku, login=<username>; pass_hash=<long string>;
    4. Paste the Cookie value to the Username field.
    5. Set Login Type to Cookie. Refer to http://i.imgur.com/rCCjnPs.png```

also upload the log file.

**Comment by lee27** [comment]
sorry, but I can not understand points 3 and 4

**Comment by Nandaka** [comment]
point 3 This one:
![image](https://user-images.githubusercontent.com/836867/31942190-1703faf6-b8f7-11e7-891f-72f6453277e0.png)
point 4. I think I skip a bit, go to your app folder and edit ```DanbooruProviderList.xml``` using text editor (e.g. notepad) and paste the cookie to username field.
![image](https://user-images.githubusercontent.com/836867/31942376-b13538f6-b8f7-11e7-80b3-b293b7a7d2ee.png)

Actually, I tried to browse without login and looks like it still working.

Can you open https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=vocaloid
It should be something like this.
![image](https://user-images.githubusercontent.com/836867/31942081-b0f5da0e-b8f6-11e7-9abf-0a684bd25029.png)

**Comment by lee27** [comment]
GREAT GREAT GRAT! WORK! THANKS

**Comment by lee27** [comment]
last question, you can, save photos in different folders, divided by tag?

**Comment by Nandaka** [comment]
only search tag, see readme.txt on Filename Format
