### ISSUE TITLE
Question about tags...

### ISSUE THREAD

**Issue by GiRaFa-SM** [Nandaka/DanbooruDownloader#143]
Which tags should i use (on sankaku) to get filenames like this: 
"yande.re 415032 sample dress katou_megumi misaki_kurehito saenai_heroine_no_sodatekata.jpg"
it seems %tags% include some of them but i end up with a long filename, i dont want that tbh. Can you give me a tip of how can i configure the program to get a filename like this?
Currently i'm using : %character%_%copyright%_drawn_by_%artist%_%md5%
Pic:
https://yande.re/post/show/415032

Thanks

**Comment by Nandaka** [comment]
Should be the same, assuming they tag the post properly in sankaku post.

https://github.com/Nandaka/DanbooruDownloader/blob/master/readme.txt#L153
https://github.com/Nandaka/DanbooruDownloader/blob/master/DanbooruDownloader3/Engine/SankakuComplexParser.cs#L143

Else, just enable the global tags xml and use yandere as your main tag list (assuming sankaku is using the same tag name).

**Comment by GiRaFa-SM** [comment]
"and use yandere as your main tag list"
Where i can find this option? Sorry for being a brainlet

**Comment by Nandaka** [comment]
Just enable the global tags xml in settings tab and update your tags.xml using yande.re as the source.

![image](https://user-images.githubusercontent.com/836867/32042362-d5de84be-ba69-11e7-8327-cc4b6663f413.png)

**Comment by GiRaFa-SM** [comment]
I did that, but i wasnt sure. It continues adding tags like "high_resolution" in the filename, but i wont complain, it may be a sankaku thing.

Thanks, can i close this issue?

**Comment by Nandaka** [comment]
set the filename limit?

**Comment by GiRaFa-SM** [comment]
There are some tags that I want to have in the file, if I set X number it would exclude some of them, right?

**Comment by Nandaka** [comment]
use Ignored Tags box? It should not use any tags defined there in the filename.

```
“Ignored Tags”     => Tags to be ignored in the filename.
                      Separate each tag with new line.
```

**Comment by GiRaFa-SM** [comment]
"Just enable the global tags xml in settings tab and update your tags.xml using yande.re as the source."

Doing this seems to have no effect in the filename, i tried both (with global tags checked and unchecked) tags still the same.

**Comment by Nandaka** [comment]
if you disable global tags.xml, it will uses their own tags information. In sankaku case, it will depends on the tag type defined in the page.

for example, the 2nd post is from sankaku and they correctly tag the post.
![image](https://user-images.githubusercontent.com/836867/37603212-55dac716-2b4b-11e8-8f99-50b8bfbf59ab.png)
result filename:
![image](https://user-images.githubusercontent.com/836867/37603162-39f3124c-2b4b-11e8-907e-5c3a0a08065d.png)
Config:
![image](https://user-images.githubusercontent.com/836867/37603237-65cd3bd6-2b4b-11e8-9d20-2531a29178ad.png)

**Comment by GiRaFa-SM** [comment]
The issue here is that even setting up using yande.re as the source, there are no changes in the filename. I deleted sankaku, gelbooru, and danbooru tags and downloaded only yande.re tags and tried to download something on sankaku, using yande.re a a source like you described and without it, still - no changes, filenames still the same. (saving the same file twice from the same booru).

**Comment by Nandaka** [comment]
Well, there are no such feature to ignore tags if not present in the xml file. The current behaviour is if it is not available in the tags.xml, then it will assigned as general/unknown tag. 

And as you said, every board will have their own set of tags for the same images, so it won't work like you want. Your best bet is just download the images and later use duplicate detector to delete the files.
