### ISSUE TITLE
Another problem with rule34hentai.net

### ISSUE THREAD

**Issue by lee27** [Nandaka/DanbooruDownloader#147]
hello, I go back with the same problem, I start full batch mode but it does not find and download nothing, I do not even bother tell me the download is completed!

![hfh](https://user-images.githubusercontent.com/20624978/32419560-1de53c02-c27c-11e7-9897-fcfc49a08cb3.png)

this is the error I get when I get "get" on "main"!

[log-2017-11-05.txt](https://github.com/Nandaka/DanbooruDownloader/files/1444483/log-2017-11-05.txt)

**Comment by lee27** [comment]
can anyone answer me?

**Comment by Nandaka** [comment]
Can you open the site? Looks like it return non-valid xml when loading http://rule34hentai.net/index.php?q=/rss/images/sarah/1

I notice it also return (503) Server non disponibile. (Service unavailable), is your isp blocking the access to the site?

I can download fine on my side, so whatever wrong must be on your side.

**Comment by lee27** [comment]
on the site I can access but the link you wrote to me, no

**Comment by lee27** [comment]
Look at the bottom on my last log
[log-2017-11-09.txt](https://github.com/Nandaka/DanbooruDownloader/files/1458495/log-2017-11-09.txt)

**Comment by Nandaka** [comment]
Your provider list looks identical with me.

I tried to open: https://rule34hentai.net/index.php?q=/rss/images/the_last_of_us/1 and it returns the image list like below:
![image](https://user-images.githubusercontent.com/836867/32642420-3279c4d0-c60f-11e7-85c1-d0830707df73.png)

Try to set a big limit when you add the batch job?
![image](https://user-images.githubusercontent.com/836867/32642531-d7856998-c60f-11e7-9639-406349b528ab.png)

**Comment by lee27** [comment]
now, I'm downloading more, set 100000 limit, but not downloading all, some 3d images jump!

**Comment by Nandaka** [comment]
the images returned from the rss api might not the latest set. It might take some time before it match with the main page (server limitation).
