### ISSUE TITLE
Full Batch Mode -> pages 50+

### ISSUE THREAD

**Issue by hardnyasha** [Nandaka/DanbooruDownloader#148]
Strange, but in Full Batch Mode, if i choose a page, like, 30 or more, it won't download anything at all. If i leave the page blank(1) or 15 it downloads as usual. Am i doing something wrong?
Log: 
[DoBatchJob] Processing Batch Job#0
[DoBatchJob] Downloading list: https://chan.sankakucomplex.com/?tags=vocaloid&page=30
[DoBatchJob] Error Getting List (1 of 20): Удаленный сервер возвратил ошибку: (404) Не найден. Wait for 60s.
[DoBatchJob] Retrying...
[DoBatchJob] Error Getting List (2 of 20): Удаленный сервер возвратил ошибку: (404) Не найден. Wait for 60s.
[DoBatchJob] Retrying...
[DoBatchJob] Error Getting List (3 of 20): Удаленный сервер возвратил ошибку: (404) Не найден. Wait for 60s.

![2017-11-13_223622](https://user-images.githubusercontent.com/33638691/32747916-19ed5e20-c8c3-11e7-9023-30be4a7521ef.png)
![2017-11-13_223605](https://user-images.githubusercontent.com/33638691/32747905-0de87d26-c8c3-11e7-8df7-75275800088a.png)

**Comment by hardnyasha** [comment]
P.S. i'm not banned on chan.sankakucomplex.com at the moment.

**Comment by Nandaka** [comment]
Have you tried this:

```
Q7: How to login to Gelbooru/Sankaku/get cookie value?
A7: Follow this step:
    1. Press F12 on your Chrome browser and select Network tab.
    2. Go to the booru site and login.
    3. Click one of the entry and copy the Cookie value from the Request Header. 
       For gelbooru, it should like this: user_id=<number>; pass_hash=<long string>
       For sankaku, login=<username>; pass_hash=<long string>;
    4. Paste the Cookie value to the Username field.
    5. Set Login Type to Cookie. Refer to http://i.imgur.com/rCCjnPs.png
```

**Comment by hardnyasha** [comment]
this one?
![2017-11-14_050958](https://user-images.githubusercontent.com/33638691/32761196-b6c06cf6-c8fa-11e7-8480-3add729b901d.png)

**Comment by Nandaka** [comment]
yep

**Comment by hardnyasha** [comment]
still getting the 404 error. everything right on this screenshot?
![2017-11-14_052241](https://user-images.githubusercontent.com/33638691/32761411-df304a98-c8fb-11e7-95c7-61319fc7a8dd.png)

**Comment by Nandaka** [comment]
weird, it is looks fine and working in my side.
![image](https://user-images.githubusercontent.com/836867/32761940-437fab44-c931-11e7-90fa-0206f17f589e.png)

**Comment by hardnyasha** [comment]
strange. seems like i'm having the same issue as in https://github.com/Nandaka/DanbooruDownloader/issues/111 
but you already fixed it. hmm, what could be the case?

**Comment by Nandaka** [comment]
Try do get the list in the main page first?
![image](https://user-images.githubusercontent.com/836867/32764378-185b8262-c940-11e7-92c8-6589e6e6b5fe.png)

Also copy the cookie value again ?

**Comment by hardnyasha** [comment]
In the main page i get the same 404 error. I don't understand it -_-

**Comment by Nandaka** [comment]
maybe your firewall/antivirus block the application? is it possible to try it on different pc?

**Comment by hardnyasha** [comment]
no, i don't have a antivirus, and the firewall does nothing, i think. 
different pc..well, i'm chatting with my friend who recommended me this program, i'll ask him if he can download after page 50.

**Comment by Nandaka** [comment]
continued in #162
