### ISSUE TITLE
problem with fullbatch mode

### ISSUE THREAD

**Issue by lee27** [Nandaka/DanbooruDownloader#149]
Why do not I find more providers?
![immagine](https://user-images.githubusercontent.com/20624978/32919827-7130c2d8-cb27-11e7-8d4e-22899dcbb513.png)

![immagine2](https://user-images.githubusercontent.com/20624978/32919900-b3eef216-cb27-11e7-86a1-ea1d6d2c056e.png)
![immagine3](https://user-images.githubusercontent.com/20624978/32919901-b412086e-cb27-11e7-9dc7-b4b01f90e771.png)

**Comment by Nandaka** [comment]
Check your DanbooruProviderList.xml file

else, get it from https://github.com/Nandaka/DanbooruDownloader/blob/master/DanbooruDownloader3/DanbooruProviderList.xml and put it in the application folder.

**Comment by lee27** [comment]
thanks a lot, but before I had more, why?

**Comment by Nandaka** [comment]
That is the default. You can add more if the site has API access.

Some booru are deleted from the default list due to site is now dead or no more API access.

**Comment by lee27** [comment]
ok thanks! last question, I'm downloading a tag of 1846 images from gelbooru, but why do not download only 817?

**Comment by Nandaka** [comment]
what is the tags?

**Comment by lee27** [comment]
mating_press

**Comment by Nandaka** [comment]
API is disabled by gelbooru, so it cannot be used for now.
https://gelbooru.com/index.php?page=forum&s=view&id=3875

**Comment by lee27** [comment]
ok thanks
