### ISSUE TITLE
add ssbooru

### ISSUE THREAD

**Issue by lee27** [Nandaka/DanbooruDownloader#150]
hello, how can i add a new host? i would like to add ssbooru!

**Comment by Nandaka** [comment]
what is the full address? if they expose danbooru API call, then I can add it to the provider list.

**Comment by lee27** [comment]
srry! http://ss.booru.org/index.php

**Comment by Nandaka** [comment]
Looks like they didn't enable the api access, so it cannot be added.

**Comment by lee27** [comment]
ok, pity, thank you very much the same!
