### ISSUE TITLE
Gelbooru Returning "No Posts!" after any search

### ISSUE THREAD

**Issue by Fash45** [Nandaka/DanbooruDownloader#151]
Whenever I set Gelbooru as my provider in the Main download no matter what I search it returns "no posts." All the other providers work. It was working fine 6  days ago but just started doing this yesterday. 

I've set login type to cookie and input my userid and passhash as described in the readme and that didn't resolved the issue.  

I'm at a loss on could be causing the issue. Any help would be appreciated. 

Log; https://pastebin.com/2LQqSi3X

**Comment by Nandaka** [comment]
from the website api
```
<response success="false" reason="Search error: API disabled due to abuse."/>
```

**Comment by Fash45** [comment]
Thanks for the quick reply.  

I had checked the forums to see if that had happened and it seems they posted that after I posted my issue here so I missed it. Thank you for the help.
