### ISSUE TITLE
it wont go over 1000 anymore with the latest version

### ISSUE THREAD

**Issue by naruhina2016** [Nandaka/DanbooruDownloader#153]
Few days ago when i tried the latest version of danbooru.
It went over 1000 on its own without any tutorials what so ever.
But now few days later it stops at 714-716.
How can i fix this please someone tell me...:(

----Naruhina2016----

**Comment by Nandaka** [comment]
upload the log file.

**Comment by naruhina2016** [comment]
[log-2017-12-05.txt](https://github.com/Nandaka/DanbooruDownloader/files/1532153/log-2017-12-05.txt)

like this?

**Comment by Nandaka** [comment]
sankaku server block you if you download too much.

> The remote server returned an error: (429) Too many requests - please slow down....

**Comment by naruhina2016** [comment]
so how can i prefend that from happening?

**Comment by Nandaka** [comment]
1. Ensure you are not blocked/banned by sankaku (check using your browser).
2. Ensure you supply the cookie values from sankaku (https://github.com/Nandaka/DanbooruDownloader/blob/master/readme.txt#L143)
3.  Set batch delay, e.g. 6000 ms (6s)
![image](https://user-images.githubusercontent.com/836867/33638426-28dc4946-da61-11e7-9b72-29cf711ba6ed.png)

It is working on my side.
![image](https://user-images.githubusercontent.com/836867/33638436-34a68ade-da61-11e7-8885-9facea261561.png)

**Comment by Nandaka** [comment]
Also note that sankaku web doesn't allow to go over 1000.

1000 is ok
![image](https://user-images.githubusercontent.com/836867/33638510-7fdab192-da61-11e7-87d5-5f3bf8ff805b.png)

1001 will return 404 not found
![image](https://user-images.githubusercontent.com/836867/33638530-9402c376-da61-11e7-9d45-122f614d200c.png)

From browser, it will return an error.
![image](https://user-images.githubusercontent.com/836867/33638556-ba874af8-da61-11e7-85eb-a633bb41a112.png)

**Comment by naruhina2016** [comment]
i am using opera browser how can i change it to that browser?

**Comment by Nandaka** [comment]
If you are using latest version of opera, it should be similar like Chrome.

**Comment by naruhina2016** [comment]
what you mean?

**Comment by Nandaka** [comment]
you asking about how to get the cookie value, right? if you asking about the browser that I'm using, it is google chrome https://www.google.com/chrome/

**Comment by naruhina2016** [comment]
cookie value is not a problem what i want to know is there a way to change the current browser to opera?

**Comment by Nandaka** [comment]
the application doesn't use any browser inside. It is using .Net Framework WebClient class.

**Comment by naruhina2016** [comment]
i see but when i used danbooru for the first it never had any problem going over 1000 so what happened?

**Comment by Nandaka** [comment]
different site different logic, different owners different rules

Danbooru and Sankaku uses different server program, so it is not the same. Similar with gelbooru.

**Comment by naruhina2016** [comment]
i see but which booru is the best to use for downloading pictures?

**Comment by Nandaka** [comment]
I have no idea for that. 
- Generally danbooru is good enough, but it will limit some tags unless you are gold member. 
- Gelbooru usually has the same content with danbooru, but they might turn off the API access so you cannot download.
- yande.re/konachan has better quality, but limited number of images.
- sankaku is kinda anything goes, but their server limit the downloads.

**Comment by naruhina2016** [comment]
so sankaku is less popular of all?

**Comment by Nandaka** [comment]
not sure, different site different target. I cannot says that sankaku is less popular than danbooru/gelbooru.

**Comment by naruhina2016** [comment]
i see if your gold member on danbooru does that mean you have to pay to become a gold member?

**Comment by Nandaka** [comment]
Yes. See https://danbooru.donmai.us/user_upgrade/new

**Comment by naruhina2016** [comment]
but still when did sankaku change their way of downloading pictures?

**Comment by Nandaka** [comment]
ask them...

**Comment by naruhina2016** [comment]
i mean they limited to 1000 but that never happened when i used your program for the first time

**Comment by Nandaka** [comment]
I have no idea, that was quite some time that they changes the ways their site works. You can ask it on their forums.

**Comment by naruhina2016** [comment]
what site do you prefer using and why?

**Comment by Nandaka** [comment]
no preferred site.

**Comment by naruhina2016** [comment]
so there isn't one  you prefer use the most?

**Comment by Nandaka** [comment]
I don't really use it anymore, I prefer to use pixiv 😄

**Comment by naruhina2016** [comment]
why pixiv?

**Comment by Nandaka** [comment]
no reason.

**Comment by naruhina2016** [comment]
lol
