### ISSUE TITLE
Question: downloading illustrations from oldest to newest first

### ISSUE THREAD

**Issue by Kira-20** [Nandaka/DanbooruDownloader#155]
Hye Nandaka, just wondering if the danboorudownloader tool has option/works how like the pixivutil does in term of downloading illustrations from oldest to newest first. If there is, mind telling me how to do that, thanks

**Comment by Nandaka** [comment]
It is depends on the board support.

For danbooru, you can refer to https://danbooru.donmai.us/wiki_pages/43049#dtext-n2-2-1

e.g. by appending `order:id_asc' on the search box.

**Comment by Kira-20** [comment]
I see, I'll give it a look and try!
