### ISSUE TITLE
if its possible to download the current page after closing off danbooru without starting all over

### ISSUE THREAD

**Issue by naruhina2016** [Nandaka/DanbooruDownloader#156]
Hi,

I was wondering if its possible to download the current page
after closing off danbooru without starting all over?
Please answer me.

----Naruhina----

**Comment by Nandaka** [comment]
If you known the last page, you can set the start page to that page?
![image](https://user-images.githubusercontent.com/836867/34778433-47408a74-f658-11e7-93a2-b6cb1f14d7bb.png)

**Comment by naruhina2016** [comment]
so i can continue download pictures from where i left off?

**Comment by Nandaka** [comment]
as long the board support page parameter, then yes.

Most of the board should support it btw.

**Comment by naruhina2016** [comment]
one last question whats parameter?

**Comment by Nandaka** [comment]
It just a term in programming, page is a parameter.

**Comment by naruhina2016** [comment]
i see thanks for your explanation...xD
