### ISSUE TITLE
Have to start all over?

### ISSUE THREAD

**Issue by AldebaraanMKII** [Nandaka/DanbooruDownloader#157]
Yesterday i downloaded about 7700 (out of 18000) images from gelbooru. I save the batch job and today loaded it again. But when i start after a minute or two a popup appears saying that the batch job is completed, but it didn't download any new files. 

Do i need to start again or there's a way to make the program skip the already downloaded files?

**Comment by Nandaka** [comment]
If you don't change the download directory and not enable the Overwrite File in the Settings tab, it should automatically skip already downloaded file (based on filename).

Also, you may need to edit the xml file using notepad
Refer to: https://github.com/Nandaka/DanbooruDownloader/issues/145#issuecomment-348078528
