### ISSUE TITLE
Web Client error

### ISSUE THREAD

**Issue by driftstick** [Nandaka/DanbooruDownloader#158]
I was start batch job and seen the error: Web Client client does not support I / O operations and uploaded too much pages "Downloaded: 283 Skipped: 3 Processed Total: 288 Total Available: 0
Current Page: 1485186 Current Page Total: 94 Offset: 0 ==> Error: WebClient client does not support I / O operations"
Whats wrong?

**Comment by Nandaka** [comment]
please give more information and upload the log file in the application folder (something like log-2018-01-12.txt)

**Comment by driftstick** [comment]
Stack Trace: 
    System.Net.WebClient.ClearWebClientState()
    System.Net.WebClient.DownloadString(Uri address)
    DanbooruDownloader3.FormMain.GetBatchImageList(String url, String query, DanbooruBatchJob job)
    DanbooruDownloader3.FormMain.DoBatchJob(BindingList`1 batchJob)
Query: butter-t
[DoBatchJob] Downloading list: https://chan.sankakucomplex.com/?tags=butter-t&page=798812&next=5115353
[DoBatchJob] Error: WebClient client does not support I / O operations".
Stack Trace: 
    System.Net.WebClient.ClearWebClientState()
    System.Net.WebClient.DownloadString(Uri address)
    DanbooruDownloader3.FormMain.GetBatchImageList(String url, String query, DanbooruBatchJob job)
    DanbooruDownloader3.FormMain.DoBatchJob(BindingList`1 batchJob)
Query: butter-t
[DoBatchJob] Batch Job Stopped.

**Comment by Nandaka** [comment]
Weird, I cannot replicate the result, btw butter-t doesn't have any post in at idolcomplex.

Are you using the latest releases? https://github.com/Nandaka/DanbooruDownloader/releases

Can you open the website from browser?
