### ISSUE TITLE
problem with settings of app

### ISSUE THREAD

**Issue by Decemviri** [Nandaka/DanbooruDownloader#159]
Hi everyone
When l use full batch mode,download picture from Sankaku,the app doesn't work properly.It can't download any picture,and only to said:
Query: fav:Lisir
[[Batch Job]] Resuming
[DoBatchJob] Downloading list: https://chan.sankakucomplex.com/post/index?tags=fav:Lisir&page=9
[DoBatchJob] Error: Cannot load tags.xml
Stack Trace: 
   在 DanbooruDownloader3.DAO.DanbooruTagsDao..ctor(String xmlTagFile)
   在 DanbooruDownloader3.DAO.DanbooruTagsDao.get_Instance()
   在 DanbooruDownloader3.Helper.ParseTags(String p, DanbooruProvider provider)
   在 DanbooruDownloader3.Engine.SankakuComplexParser.Parse(String data, DanbooruSearchParam searchParam)
   在 DanbooruDownloader3.DAO.DanbooruPostDao..ctor(Stream input, DanbooruPostDaoOption option)
   在 DanbooruDownloader3.FormMain.GetBatchImageList(String url, String query, DanbooruBatchJob job)
   在 DanbooruDownloader3.FormMain.DoBatchJob(BindingList`1 batchJob)

Somebody can help me?

**Comment by Nandaka** [comment]
download the tags.xml from here: https://github.com/Nandaka/DanbooruDownloader/releases/download/v3.20161114/tags-danbooru.20161114.7z 

It is the old one, otherwise you can download it from Settings -> Update Tags.xml. It is recommended to use yande.re as the tags source.

**Comment by Decemviri** [comment]
Thanks a lot,l got it.
Moreover,l have downloaded tags from ＃126 and unpack this tags in DanBooru's downloader folder,but don't kown what to do next.
Would you give some suggestions?

**Comment by Nandaka** [comment]
If you have updated the tags.xml via Settings, then you don't need the one from the releases.

**Comment by Decemviri** [comment]
Ok,thanks
