### ISSUE TITLE
Issue please help / advise.

### ISSUE THREAD

**Issue by spidernope** [Nandaka/DanbooruDownloader#165]
Every imageboard works fine except one.

Rule34hentai.net won't let me view content on the main tab or bulk download.

I get the following error when I seach a tag on the main tab.

![capture](https://user-images.githubusercontent.com/39782214/40753645-6eb65ada-6475-11e8-9911-e68137091314.JPG)

**Comment by Nandaka** [comment]
try to copy https://github.com/Nandaka/DanbooruDownloader/blob/master/DanbooruDownloader3/xhtml.ent to the application folder.

**Comment by spidernope** [comment]
Thank you Nandaka. Copying and pasting that code into the xhtml.ent file solved the issue. Thank you!
