### ISSUE TITLE
no tag type for e621

### ISSUE THREAD

**Issue by yami-no-tusbas** [Nandaka/DanbooruDownloader#167]
Hellow, thx for your amazing program.
I started using it on e621 somes days ago and... There is the problem, i can't use %artist% or %character%, on this website, they are just empty. i use them for organising collection, it work fine on gelbooru and danbooru type boards, but won't work on e621.

for exemple if i use : "%provider%\%copyright%\%character%\%artist% - %rating% - %id%" : 
this image "https://e621.net/post/show/1590328" should have been tagged by artist senz, but is not, the image was in "Multiple Copyright\ruby_(steven_universe)\ - s - 1590328.png" 

all grouping limit are at 2 in my settings, and worked for copyright, then it should have been in multiple characters, but no... it taked "ruby" but none of the other two. Then we have the file name : " - s - 1590328" rating and id worked, but again, artist didn't...

on this one : https://e621.net/post/show/1585757 the artist worked : "nerd - s - 1585757.png" and it was in "Danbooru Downloader\e621 (Furry)\Multiple Copyright\Multiple Character" so times to times it work, other times it don't... maybe a problem with e621.

and btw, is it posible to have tags type specifics to e621 like species ? (cf :https://e621.net/tag?name=&type=5&order=count)

**Comment by yami-no-tusbas** [comment]
I made som testing, and It looks like something is wrong with you app. When i get tags frome gelboorum, it go trought all the pages. But, from e621, It only take 1 page, then merge to tags.xml. It doesn't get all the tags, limit "0" don't work either, the max limit is "500" on e612.net.

Why you app don't go trough all the pages like It does on gelbooru ?

tags url = https://e621.net/tag/index.xml?limit=500&page=1
Loop can't be check. I can download page "one by one" but it doesn't event merge them, it just replace the previous result with the new ones.

**Comment by Nandaka** [comment]
for some reason, e621 use different structure in the tags.xml format.
![image](https://user-images.githubusercontent.com/836867/45367923-e4430a00-b614-11e8-9335-cae7d21caf96.png)

Compared with danbooru and gelbooru, which uses almost the same structure.
![image](https://user-images.githubusercontent.com/836867/45367962-fb81f780-b614-11e8-8b68-ca6ae5f6379a.png)
![image](https://user-images.githubusercontent.com/836867/45367973-0177d880-b615-11e8-81b7-4dbdc61791aa.png)

So no support for e621

**Comment by yami-no-tusbas** [comment]
well, I've found another grabber that work on gelbooru and e621 just fine. Guess I'll stop using yours.

**Comment by Nandaka** [comment]
Sure, may I know which one you are using, so I can also recommend those for other e621 users?
