### ISSUE TITLE
No "character" tag problem

### ISSUE THREAD

**Issue by yami-no-tusbas** [Nandaka/DanbooruDownloader#168]
I just see that, this image "https://gelbooru.com/index.php?page=post&s=view&id=2909423" as no "character tags", then the file name is : "urepito_honke - Multiple Character - q - 2909423.png". It's a bit annoying to sort images ^^'

Can you make it so empty character is tagged as "no_character" something like that ?

btw : "https://gelbooru.com/index.php?page=post&s=view&id=3961862" as it "character" leaved as a blank in the file name. ("starcross -  - e - 3961862.png")

**Comment by Nandaka** [comment]
what is your tags.xml source? Also try to enable `Use Colored Tags` in the setting pages and see if the tags is detected as character tag?

**Comment by Nandaka** [comment]
running using attached tags.xml return proper tag
![image](https://user-images.githubusercontent.com/836867/42580225-a418bfc6-855c-11e8-936d-96f5a0258b0c.png)
[tags-gelbooru.com.zip](https://github.com/Nandaka/DanbooruDownloader/files/2184981/tags-gelbooru.com.zip)

**Comment by yami-no-tusbas** [comment]
I got the same result, but starcross is not the artist btw, starcross is pink, so artist tag, but it is not. The artist is "urepito honke". And there is no "character" in the original image, i's empty look the tags on gelbooru :
Artist
? urepito honke 52
Copyright
? original 453260
Metadata
? absurdres 266604
? highres 1345033
Tag...
There is no character and your program get the artist wrong. It will not detect character, because there is not in fact. That's why I ask if it can replace "void" character by "no_character" or somthing like that.
![pzjzewc](https://user-images.githubusercontent.com/3921598/42731885-ea3b6406-8816-11e8-8b4d-ba2474978254.jpg)

**Comment by Nandaka** [comment]
try latest version: https://github.com/Nandaka/DanbooruDownloader/releases/tag/v3.20180721

**Comment by Nandaka** [comment]
Weird, it is resolved properly in my pc. Is the tag detected correctly? The tag detection is depends on tags.xml

Main Tab result (notice the pink tag):
![image](https://user-images.githubusercontent.com/836867/43142521-2f76233c-8f8b-11e8-80f6-9a08050ed5cf.png)

Download Tab result
![image](https://user-images.githubusercontent.com/836867/43142548-405ce4c4-8f8b-11e8-917b-09d999223800.png)

Settings:
![image](https://user-images.githubusercontent.com/836867/43142563-49155808-8f8b-11e8-88fe-29f9fcbcc5b9.png)

**Comment by yami-no-tusbas** [comment]
Yeah tag.xml... new download, so i just forgot to download the tags, i'm so dumb ! it's working fine now ! Sry for making you loose your time.
