### ISSUE TITLE
rule34hentai problem

### ISSUE THREAD

**Issue by lee27** [Nandaka/DanbooruDownloader#170]
Hello everyone, I was trying to download the tag "life is strange" using the batch mode (rule34 hentai), for this tag I counted a total of 1792 images on the site, but because in total, danbooru downloader I download only 1680? thank you

**Comment by Nandaka** [comment]
the image list is retrieved using rss url (e.g. https://rule34hentai.net/index.php?q=/rss/images/life_is_strange/1) so the count might be different as the update from server is not always the latest

**Comment by Nandaka** [comment]
usually you need to wait before the new images available from rss api.

**Comment by lee27** [comment]
so there is no real way to download all the photos, could you try it yourself?

**Comment by Nandaka** [comment]
nope, it is depend on the api provided by the site.
