### ISSUE TITLE
rule34.paheal.net - Error 404

### ISSUE THREAD

**Issue by Alkl58** [Nandaka/DanbooruDownloader#172]
Log:

> 2018-07-20 10:23:40,417 INFO  - Starting up Danbooru Downloader 3.2017.09.22
> 2018-07-20 10:23:40,417 DEBUG - Loading provider list.
> 2018-07-20 10:23:40,455 DEBUG - Provider list loaded.
> 2018-07-20 10:23:40,455 DEBUG - Danbooru Downloader 3.2017.09.22 loaded.
> 2018-07-20 10:24:06,280 INFO  - [DoBatchJob] Processing Batch Job#0
> 2018-07-20 10:24:06,343 INFO  - [DoBatchJob] Downloading list: http://rule34.paheal.net/index.php?q=/rss/images/YoRHa_No.2_Type_B/1
> 2018-07-20 10:24:07,324 ERROR - [DoBatchJob] Error Getting List (1 of 5): Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden. Wait for 60s.
> System.Net.WebException: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
>    bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
>    bei System.Net.WebClient.DownloadString(Uri address)
>    bei DanbooruDownloader3.FormMain.GetBatchImageList(String url, String query, DanbooruBatchJob job)
> 2018-07-20 10:25:07,520 INFO  - [DoBatchJob] Retrying...

Solution:

![old-new](https://user-images.githubusercontent.com/34812414/43023300-a7ded6ee-8c6a-11e8-8bee-77b1fc2a0f3b.PNG)
(left old; right new - With this solution I've managed to get the list in the Main Tab but it doesn't work for Batch Download)

**Comment by Ouxhi** [comment]
I'm having an issue with pahael also.  I didn't create a separate ticket because I believe the issues might be related. 

Error code from log:
[clientThumb_DownloadDataCompleted] Error69 The request was aborted: Could not create SSL/TLS secure channel. 

I didn't try using the batch download, just tried to manually add images to the download list.

**Comment by Nandaka** [comment]
@Ouxhi Can you open the site (https) from browser? Are you using winxp?

**Comment by Ouxhi** [comment]
I opened https://rule34.paheal.net/ on Firefox and Chrome without any issues. I could see all the posts on the site and there weren't any issues navigating through different pages. I'm not using winxp, I'm using Windows 10.

**Comment by Nandaka** [comment]
found the issue, need to recompile with .net4.5, I'll upload the new version soon.

@Alkl58 https://rule34.paheal.net/rss/images/YoRHa_No.2_Type_B/1 << this one should be working in the new version

**Comment by Nandaka** [comment]
Try https://github.com/Nandaka/DanbooruDownloader/releases/tag/v3.20180721

**Comment by Ouxhi** [comment]
The new release seems to have resolved my issue. I'm no longer receiving an error message while the list is populating.

**Comment by Alkl58** [comment]
Thank you very much! It works now perfectly well!

**Comment by RikisX** [comment]
>_< DanbooruDownloader20180721 doesn't work for this:
[DoBatchJob] Processing Batch Job#0
[DoBatchJob] Downloading list: https://danbooru.donmai.us/post/index.xml?tags=zumi_(zumidraws)&limit=1000&page=1
....(get's images from different server)....
[DoBatchJob] Download: https://hijiribe.donmai.us/data/bc41854e29a6fb490a4c2947809e752b.jpg
[DoBatchJob] Error Download Batch Image (0 of 5): The request was aborted: Could not create SSL/TLS secure channel. 

DanbooruDownloader20170906 works fine.
Borked TLS1.2 certificate? Firefox and chrome opens image, IE 11 doesn't, unless I disable TLS 1.2.
Windows 7 x64, Microsoft .NET Framework 4.7.2
This says it should work on IE11 Win7 with TLS 1.2: https://www.ssllabs.com/ssltest/analyze.html?d=hijiribe.donmai.us , but it doesn't.

**Comment by Nandaka** [comment]
maybe, because I set the supported encrypt to tls12
https://github.com/Nandaka/DanbooruDownloader/commit/35af93846af8ac0e1989efa83ae95196ff8e26c2#diff-94f877bda1f53e3066e9e0a0a7d875a0R19

**Comment by Nandaka** [comment]
possible solution to edit DanbooruProviderList.xml using notepad and replace https with http?

**Comment by RikisX** [comment]
I fail to find solution.
**http**://danbooru.donmai.us/post/index.xml?tags=zumi_(zumidraws)&limit=1000&page=1
Still returns: **https**://hijiribe.donmai.us/data/

Made DanbooruDownloader20170906 work for rule34.paheal.net with registry entries: 

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v2.0.50727]
"SystemDefaultTlsVersions"=dword:00000001
"SchUseStrongCrypto"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v4.0.30319]
"SystemDefaultTlsVersions"=dword:00000001
"SchUseStrongCrypto"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v2.0.50727]
"SystemDefaultTlsVersions"=dword:00000001
"SchUseStrongCrypto"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v4.0.30319]
"SystemDefaultTlsVersions"=dword:00000001
"SchUseStrongCrypto"=dword:00000001
```
and

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client]
"DisabledByDefault"=dword:00000000

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server]
"DisabledByDefault"=dword:00000000

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client]
"DisabledByDefault"=dword:00000000

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server]
"DisabledByDefault"=dword:00000000

```

**Comment by Nandaka** [comment]
It return danbooru for me.
Try to key in the login information for danbooru? You can use the Cookie Method from readme.
https://github.com/Nandaka/DanbooruDownloader/blob/master/readme.txt#L143

**Comment by RikisX** [comment]
With cookie or without it's same:
```
[DoBatchJob] Downloading list: http://danbooru.donmai.us/post/index.xml?tags=mario_wibisono&limit=1000&page=1
[DoBatchJob] Download: https://hijiribe.donmai.us/data/6e627659e345c68ee934cbafd176bf2d.jpg
[DoBatchJob] Error Download Batch Image (0 of 5): The request was aborted: Could not create SSL/TLS secure channel. Wait for 60s.
[DoBatchJob] Retrying...
[DoBatchJob] Error Download Batch Image (1 of 5): The request was aborted: Could not create SSL/TLS secure channel. Wait for 60s.
```
That hijiribe server serving only some images and it seems it's only one which I have issues with.

**Comment by Alkl58** [comment]
Alot time has passed. Sorry for closing it so late.

**Comment by poojashrama09** [comment]
I have brought a very just article for you, which you will really like, it will also be useful for you.
https://dhanvekumari.wixsite.com/mumbai-escorts
https://sites.google.com/view/hotdehradunescort/mumbai-escorts
https://hotraipurescorts.mystrikingly.com/mumbai-escorts
https://mumbaiescorts59.godaddysites.com/
https://itsnatashaarora.wixsite.com/bangalore-escorts
https://mumbaiescorts2429.godaddysites.com/my-blogs/f/chennai-call-girls
http://mumbiaescort.website3.me/chennai-escorts
https://sites.google.com/view/hotchennaicallgirls/ 
http://chennai-escorts.wikidot.com/
https://chennai-call-girls.jigsy.com/ 
https://dhanvekumari.wixsite.com/mumbai-escorts/post/chennai-call-girls 
https://mumbaiescorts.websites.co.in/ 
http://mumbiaescort.website3.me/ 
https://dhanvekumari.wixsite.com/mumbai-escorts/post/chennai-call-girls/ 
https://escortsinmumbai.bcz.com/
https://hotdehraunescorts.wixsite.com/dehradunescorts/post/hot-raipur-escorts
https://63a5633b14981.site123.me/ 
https://whatsaapnumber.wixsite.com/bhabhiwhatsappnumber
https://bhabhiwhatsappnumber.edublogs.org/ 
http://escortsinchennai.freeescortsite.com/ 
https://itsnatashaarora.wixsite.com/bangalore-escorts/post/chennai-call-girls 
https://hotcallgirl.escortbook.com/
