### ISSUE TITLE
All Sankaku Tags (18.226 tmp files & Merged files) (Download links) & other Tags

### ISSUE THREAD

**Issue by Alkl58** [Nandaka/DanbooruDownloader#173]
I noticed that the #126  tags are sometimes quite different, when you download it manually. So I decided to do an update:

Download Sankaku tmp files (7z): https://mega.nz/#!HPAXiQpa!KoP3-riFVTJngcQIV5ta-zp9OPAdEfLGSOHQeGAkGgE
Download Sankaku merged file (7z): https://mega.nz/#!2aBzhQIJ!q96XOpnW5T8dhklUxhS5YoQSfdoujax7mC2lmhppI9U

Other Tags will be added in the following days:
Other Tags (Folder): https://mega.nz/#F!KOYxmABL!9G5ff5EkVFGN7pNm1NRPIA

I try to update these Tags in a period of 1 to 2 month.

**Comment by Nandaka** [comment]
You don't need to download sankaku tags, if you follow the step in https://github.com/Nandaka/DanbooruDownloader/blob/master/readme.txt#L154
