### ISSUE TITLE
how i use this?

### ISSUE THREAD

**Issue by thegodford** [Nandaka/DanbooruDownloader#177]
Hello, I'm new at this,
I would like to know how to use this program since I downloaded it but not how to open it

**Comment by Nandaka** [comment]
Assuming you are using windows 7 or up.

1. Download the latest version from: https://github.com/Nandaka/DanbooruDownloader/releases
2. Extract it to some folder, e.g. C:\DanbooruDownloader.
3. Run the executables, it will ask you to download the tags.xml for the 1st time. You can use yande.re as the source.
4. In the main tab, you can key in the search tags to get the list of the images and select the images to download.
5. Or use the batch download to download all matching images.
