### ISSUE TITLE
Sankaku batch download missing images.

### ISSUE THREAD

**Issue by ShinRaikdou** [Nandaka/DanbooruDownloader#178]
For example "daisy_(dq)" tag has 124 images based on browser, but batch download processing only 119. Do I miss something? 
https://i.imgur.com/zCYMDyo.png
https://i.imgur.com/rHkx0pg.png
And this is one of the examples, other tags also has fewer processed images than browser ("mage_(dq3)" 288 vs 281).
Tried with and without sankaku account. Here is my settings:
https://i.imgur.com/F5BCaEr.png

**Comment by Nandaka** [comment]
can you check the log file and see if some images are skipped.

**Comment by ShinRaikdou** [comment]
Nothing is skipped. Main tab with preview also has same quantity as batch download.
Here is log without links
`
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[mawaru_(mawaru)][daisy_(dq)][7141000][s].png
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[][daisy_(dq)][7084037][s].png
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[][daisy_(dq)][7083590][q].png
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[sakuradou][daisy_(dq)][6331925][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[sakuradou][daisy_(dq)][6331924][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[sakuradou][daisy_(dq)][6331923][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[lee_(dragon_garou)][abel_(dq) daisy_(dq) slime_(dragon_quest)][6179550][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[tenpou_gensui][MCh][6090179][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[ryunryun][daisy_(dq)][5853122][s].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[kitajima_kitarou][daisy_(dq)][5851284][s].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[kumikouj][daisy_(dq)][5851283][s].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[fushisha_o][abel_(dq) daisy_(dq)][5842892][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[][daisy_(dq)][5842888][s].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[smile40_(ogi)][daisy_(dq)][5842886][s].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[kujira_gunsou][daisy_(dq)][5842883][s].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[smile40_(ogi)][daisy_(dq)][5842878][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[freedom_nakai][daisy_(dq)][5842874][s].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[][abel_(dq) daisy_(dq) tialah][5840971][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[aqua_elf][daisy_(dq)][5840948][s].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[shuninshunin][daisy_(dq)][5840943][s].gif
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[damedungeon][daisy_(dq)][5840901][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[takerunoyebisu][daisy_(dq)][5840899][s].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[sorashu][daisy_(dq)][5840893][s].png
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[sorashu][daisy_(dq)][5838701][s].png
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[yumurama][daisy_(dq)][5838698][q].png
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[mizunoto_kanae][daisy_(dq)][5838696][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[amania_orz][daisy_(dq)][5815867][s].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[tsuki_wani][daisy_(dq)][5769483][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[][daisy_(dq)][5689591][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[][daisy_(dq)][5611363][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[][daisy_(dq)][5230182][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[sunahara_wataru][daisy_(dq) maam][4782365][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[amakara_de_ikou][daisy_(dq)][4726535][e].png
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[amakara_de_ikou][daisy_(dq)][4726534][e].png
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[amakara_de_ikou][daisy_(dq)][4726533][e].png
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[amakara_de_ikou][daisy_(dq)][4726531][e].png
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[amakara_de_ikou][daisy_(dq)][4726530][e].png
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[amakara_de_ikou][daisy_(dq)][4726529][e].png
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[amakara_de_ikou][daisy_(dq)][4726528][e].png
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[horikoshi_kouhei][daisy_(dq)][4607140][s].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[ojo_(dfreak)][daisy_(dq)][4569492][s].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[nanba_(tanishi)][daisy_(dq)][4523016][s].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[][daisy_(dq)][4334724][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[][daisy_(dq)][4334721][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[][daisy_(dq)][4334719][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[][daisy_(dq)][4334711][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[][daisy_(dq)][4334700][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[][daisy_(dq)][4334699][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[][daisy_(dq)][4334696][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[][daisy_(dq)][4334692][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[][daisy_(dq)][4334691][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[][daisy_(dq)][4334686][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[][daisy_(dq)][4282381][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[][daisy_(dq)][4282376][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[][daisy_(dq)][4187861][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[ootsuki_wataru][daisy_(dq)][4185194][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[][daisy_(dq)][4177331][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[pandoras_box][daisy_(dq)][4128467][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[pandoras_box][daisy_(dq)][4128463][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[oreteki18kin][daisy_(dq)][4056072][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[oreteki18kin][daisy_(dq)][4056070][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[sakuradou][daisy_(dq)][3971166][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[koi_tsuka][daisy_(dq)][3870934][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[amakara_de_ikou][daisy_(dq)][3860261][e].png
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[amakara_de_ikou][daisy_(dq)][3853541][e].png
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[onomeshin][daisy_(dq)][3625163][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[inja_no_kuruwa urakan][daisy_(dq)][3533730][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[sakuradou][daisy_(dq)][3491003][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[sakuradou][daisy_(dq)][3491002][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[][daisy_(dq)][3383890][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[mokomoko][abel_(dq) daisy_(dq) tialah yanak][3383879][s].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[fumio_(rsqkr)][daisy_(dq)][3361696][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[pao_(otomogohan)][daisy_(dq)][3350307][s].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[nekoguchi][daisy_(dq)][3155825][s].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[][daisy_(dq)][3155821][s].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[][daisy_(dq)][3155818][s].png
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[j.u][daisy_(dq)][3155009][s].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[agahari][daisy_(dq)][2648241][s].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[akira02][daisy_(dq)][1865574][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[akira02][daisy_(dq)][1829967][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[amakara_de_ikou][daisy_(dq)][1614680][e].png
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[oreteki18kin][daisy_(dq)][1588285][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[][daisy_(dq) tialah][1432105][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[][daisy_(dq)][1429974][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[][daisy_(dq)][1421000][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[bang-you][daisy_(dq) manya soldier_(dq3)][1404470][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[mokomoko toriyama_akira][abel_(dq) daisy_(dq) tialah yanak][1374728][s].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[][daisy_(dq)][1213843][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[irotsuya][daisy_(dq)][1212069][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[o_p.com opocom][daisy_(dq) torneko torneko_taloon][1212050][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[arisawa_masaharu][daisy_(dq)][814833][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[doguu mimizou][MCh][753475][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[enomoto_hidehira hanae_shuuhei][daisy_(dq)][714043][s].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[amawa_kazuhiro][daisy_(dq)][714041][s].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[haruyama haruyama_kazunori][daisy_(dq)][619265][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[][daisy_(dq)][618653][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[][daisy_(dq)][618584][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[][daisy_(dq)][618533][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[ero_shocker][daisy_(dq)][618469][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[][daisy_(dq)][618436][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[][daisy_(dq)][618430][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[][daisy_(dq)][618208][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[bang-you][daisy_(dq) soldier_(dq3)][513699][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[][daisy_(dq)][504433][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[][daisy_(dq)][504431][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[][daisy_(dq)][504427][s].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[][daisy_(dq)][504424][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\q\[aitanikofu][daisy_(dq)][492081][q].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[teriyaki][daisy_(dq)][431220][s].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[][daisy_(dq)][427286][s].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[tarayama yuki_taru][daisy_(dq)][423631][s].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[maagori][daisy_(dq)][365946][s].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\s\[][daisy_(dq)][357104][s].png
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[sakuradou][daisy_(dq)][339667][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[bang-you][daisy_(dq) soldier_(dq3)][266616][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[bang-you][daisy_(dq) soldier_(dq3)][266035][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[bang-you][daisy_(dq) soldier_(dq3)][265971][e].jpg
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[tenseiani][daisy_(dq)][36886][e].png
[DoBatchJob] Saved To: D:\!G_SORT\S_Down\daisy_(dq)2\e\[][daisy_(dq)][11139][e].png
[DoBatchJob] No more image.
[DoBatchJob] Batch Job #0: Done
`

**Comment by ShinRaikdou** [comment]
Checked every images one by one, and it seems browser also has 119 images showed, even though its marked 124. Is this bug on Sankaku part?

**Comment by Nandaka** [comment]
maybe the post count contains deleted images in their server? or maybe the index of the post count is not updated. Anyway, looks like this more on their server side issue then.
