### ISSUE TITLE
Batch Download from Gelbooru won't go past 20000

### ISSUE THREAD

**Issue by jake1478** [Nandaka/DanbooruDownloader#186]
I'm trying to batch download from a category, but I can't go past 20k, the job in the program turns red and won't download anything else. Any thoughts?

**Comment by Nandaka** [comment]
most likely api/user limit. 
From other downloader issue tracker: https://github.com/mikf/gallery-dl/issues/56

Same story for danbooru.
https://donmai.us/forum_topics/11576
https://donmai.us/wiki_pages/43574

**Comment by jake1478** [comment]
So reading that, it seems like somehow using the gelbooru api would let me get passed that 20k limit? Is that possible? (sorry I'm not very knowledgeable about this stuff)

**Comment by Nandaka** [comment]
Nope, the application already uses Gelbooru API, trying to load more than 20k will return empty data.

For example: https://gelbooru.com/index.php?page=dapi&s=post&q=index&pid=201

**Comment by jake1478** [comment]
Ah, I see. Thank you for answering my question. :)
