### ISSUE TITLE
problem with rule34hentai.net

### ISSUE THREAD

**Issue by lee27** [Nandaka/DanbooruDownloader#204]
hi everyone, I have the following problem with the rule34hentai.net provider, when I do the batchmode I have this error

System.Xml.XmlException: The start tag 'meta' on line 9, position 4 does not match the end tag of 'head'. Row 76, position 3.
   in System.Xml.XmlTextReaderImpl.Throw (Exception e)
   in System.Xml.XmlTextReaderImpl.ThrowTagMismatch (NodeData startTag)
   in System.Xml.XmlTextReaderImpl.ParseEndElement ()
   in System.Xml.XmlTextReaderImpl.ParseElementContent ()
   in System.Xml.Linq.XContainer.ReadContentFrom (XmlReader r)
   in System.Xml.Linq.XContainer.ReadContentFrom (XmlReader r, LoadOptions o)
   in System.Xml.Linq.XDocument.Load (XmlReader reader, LoadOptions options)
   in DanbooruDownloader3.Engine.ShimmieEngine.ReadRssMethod2 (DanbooruPostDaoOption option, BindingList`1 posts, String xmldoc)
   in DanbooruDownloader3.Engine.ShimmieEngine.ParseRSS (String xmldoc, DanbooruPostDaoOption option)
   in DanbooruDownloader3.DAO.DanbooruPostDao.ProcessXML (String rawData)
   in DanbooruDownloader3.DAO.DanbooruPostDao..ctor (Stream input, DanbooruPostDaoOption option)
   in DanbooruDownloader3.FormMain.clientList_DownloadDataCompleted (Object sender, DownloadDataCompletedEventArgs e)
   in System.Net.WebClient.OnDownloadDataCompleted (DownloadDataCompletedEventArgs e)

**Comment by Nandaka** [comment]
see #200

**Comment by lee27** [comment]
unfortunately it continues to give me the same mistake
