### ISSUE TITLE
rule34 problem

### ISSUE THREAD

**Issue by lee27** [Nandaka/DanbooruDownloader#205]
sorry, nandaka, you closed the post and not so if you continued reading, unfortunately it continues to give me the same problem!
hi everyone, I have the following problem with the rule34hentai.net provider, when I do the batchmode I have this error
------------------------------
System.Xml.XmlException: The start tag 'meta' on line 9, position 4 does not match the end tag of 'head'. Row 76, position 3.
in System.Xml.XmlTextReaderImpl.Throw (Exception e)
in System.Xml.XmlTextReaderImpl.ThrowTagMismatch (NodeData startTag)
in System.Xml.XmlTextReaderImpl.ParseEndElement ()
in System.Xml.XmlTextReaderImpl.ParseElementContent ()
in System.Xml.Linq.XContainer.ReadContentFrom (XmlReader r)
in System.Xml.Linq.XContainer.ReadContentFrom (XmlReader r, LoadOptions o)
in System.Xml.Linq.XDocument.Load (XmlReader reader, LoadOptions options)
in DanbooruDownloader3.Engine.ShimmieEngine.ReadRssMethod2 (DanbooruPostDaoOption option, BindingList`1 posts, String xmldoc)
in DanbooruDownloader3.Engine.ShimmieEngine.ParseRSS (String xmldoc, DanbooruPostDaoOption option)
in DanbooruDownloader3.DAO.DanbooruPostDao.ProcessXML (String rawData)
in DanbooruDownloader3.DAO.DanbooruPostDao..ctor (Stream input, DanbooruPostDaoOption option)
in DanbooruDownloader3.FormMain.clientList_DownloadDataCompleted (Object sender, DownloadDataCompletedEventArgs e)
in System.Net.WebClient.OnDownloadDataCompleted (DownloadDataCompletedEventArgs e)

**Comment by Nandaka** [comment]
yes, I won't do anything because it is being protected by cloudflare.

See #200 for work around.
