### ISSUE TITLE
Downloading from Danbooru meets ISP block

### ISSUE THREAD

**Issue by seija99** [Nandaka/DanbooruDownloader#208]
Hi, so to start I usually access danbooru using DNSCrypt. Opening the site from browser works just fine with DNSCrypt on, but the downloader itself seems to be met with ISP block. This only happened more or less this week, I did some downloads on march 5 just fine. Any idea what's causing this?

Here are the query dump and log files.
[Dump for List danbooru Query .txt](https://github.com/Nandaka/DanbooruDownloader/files/4352489/Dump.for.List.danbooru.Query.txt) => seems to be MyRepublic ISP block page?
[log-2020-03-19.txt](https://github.com/Nandaka/DanbooruDownloader/files/4352490/log-2020-03-19.txt)

Thanks for the help.

**Comment by Nandaka** [comment]
use Simple DnsCrypt?

**Comment by lisiado5** [comment]
> utilizar Simple DnsCrypt?

so it seems there are problems with some of the providers, like sankaku or e621

**Comment by seija99** [comment]
So, an update as I found this accidentally today 3/22.
I tried downloading again with DNSCrypt.
Some tests I did:
1. With 1 artist manually added in add batch job menu - **success**
[log-2020-03-22_1artistnobatchlist.txt](https://github.com/Nandaka/DanbooruDownloader/files/4364408/log-2020-03-22_1artistnobatchlist.txt) => from line 137
![DanbooruDownloader3_jRiBI6rnr1](https://user-images.githubusercontent.com/62314255/77238533-5d0c2480-6c03-11ea-8138-9f8e7dfa4476.png)
2. With 1 artist saved in a batch list .xml - **success**
[log-2020-03-22_testbatchlist.txt](https://github.com/Nandaka/DanbooruDownloader/files/4364409/log-2020-03-22_testbatchlist.txt)
[testbatchlist.txt](https://github.com/Nandaka/DanbooruDownloader/files/4364415/testbatchlist.txt) => xml batch
![DanbooruDownloader3_IkZFBcXqrO](https://user-images.githubusercontent.com/62314255/77238558-a2c8ed00-6c03-11ea-8ee4-4caf200d72fb.png)
3. With my main 140+ artist list - **fail**
[log-2020-03-22.txt](https://github.com/Nandaka/DanbooruDownloader/files/4364411/log-2020-03-22.txt)
[artist_list.txt](https://github.com/Nandaka/DanbooruDownloader/files/4364420/artist_list.txt) => main batch .xml

**Comment by Nandaka** [comment]
your old list is still using http, change it to https.

**Comment by seija99** [comment]
Alright lol that finally works. Now I can update my archive. Thanks for the help!
