### ISSUE TITLE
chan cankaku username and password hash

### ISSUE THREAD

**Issue by 0lm** [Nandaka/DanbooruDownloader#211]
hello. to overcome the "25 pages limit" while downloading from chan sankakucomplex, i need to enter the username and password hash.
so there are 2 fields in the edit:
1. UserName
2. Password
how exactly do i need to fill these fields? i will make examples and i hope someone can tell me if it was right. (i ask this because i somehow cant get it to work. there are probably a few mor combinations, but i think you understand what i try to say. could someone give me the right example how to fill these 2 fields?)

Example 1:
Username: login=USER;
Password: pass_hash=000000000;

Example 2: (without semicolon)
Username: login=USER
Password: pass_hash=000000000

Example 3:
Username: USER
Password: 000000000

Example 4:
Username: USER
Password: pass_hash=000000000;

example 5: (without semicolon)
Username: USER
Password: pass_hash=000000000

**Comment by Nandaka** [comment]
see the readme, Q7

**Comment by 0lm** [comment]
i did look at Q7. and finally after looking even closer at the screenshot i understood: the red lines totally cover the "password field". thats why i was thinking that the screenshot is old and i need to enter the stuff seperately into username and password fields now, which caused it not to work obviously.

it worked now but maybe a better screenshot could help other/new users, since the red boxes are kind of confusing, making you think the screenshot is form an old version which didnt have a password field.
