### ISSUE TITLE
The next page cannot be automatically loaded when searching

### ISSUE THREAD

**Issue by xuejianxianzun** [Nandaka/DanbooruDownloader#217]
I click the `Get` button in the **main** panel, it only loads the first page, and it does not load automatically. When I click the next page button `>`, the next page is loaded. I didn't find a solution, what should I do?
Provider is Sankaku Complex (Idol).

**Comment by Nandaka** [comment]
![image](https://user-images.githubusercontent.com/836867/85195908-f9c88600-b308-11ea-8384-19938212281b.png)
Ensure both are enabled. It will try to load the next page when you scroll down at the end of the list.

**Comment by xuejianxianzun** [comment]
> ![image](https://user-images.githubusercontent.com/836867/85195908-f9c88600-b308-11ea-8384-19938212281b.png)
> Ensure both are enabled. It will try to load the next page when you scroll down at the end of the list.

Thank you, I know that when I drag the scroll bar to the bottom, it will automatically load the next page. But the total number of pages is too much, so the operation takes a lot of time.
Can it be automatically loaded to the specified number of pages? This can be very convenient if possible.

**Comment by xuejianxianzun** [comment]
> ![image](https://user-images.githubusercontent.com/836867/85195908-f9c88600-b308-11ea-8384-19938212281b.png)
> Ensure both are enabled. It will try to load the next page when you scroll down at the end of the list.

I see, I should use batch mode, thank you!
