### ISSUE TITLE
Can´t download from sankaku complex

### ISSUE THREAD

**Issue by Frito-Lay74** [Nandaka/DanbooruDownloader#237]
Hello, today I tried to do a couple of batch downloads from sankaku but every single image gets skipped. In the log all the images say "no file url or probably deleted" which is weird because the images can be seen without problem in a web browser. I could do batch jobs yesterday without any problem.
Could this issue be related with this one? #236 

Any help would be greatly appreciated.

**Comment by Nandaka** [comment]
duplicate with #236
