### ISSUE TITLE
I cant Log in with sankaku

### ISSUE THREAD

**Issue by NickSpike34** [Nandaka/DanbooruDownloader#243]
I've been trying to download from page 25, but as much as I try to log in with my account, I can't download from that page, I did everything as Q7 says and it still won't let me download from page 25
![san error](https://user-images.githubusercontent.com/88297526/127793607-a6fe37ab-0c67-4cc8-b2cc-4309fafe0f51.png)
![san error 2](https://user-images.githubusercontent.com/88297526/127793669-3d10a638-7d3b-4e0f-95f8-61d05e6245b1.png)

**Comment by Nandaka** [comment]
Ah, you need to copy the whole cookie string now. I will update the readme.
![image](https://user-images.githubusercontent.com/836867/127818929-7ebec39f-6680-4933-bb18-38ee5a89083b.png)

**Comment by NickSpike34** [comment]
Thanks! That worked
