### ISSUE TITLE
Full Batch Mode bug, causing the app to blink nonstop

### ISSUE THREAD

**Issue by Romangelo** [Nandaka/DanbooruDownloader#250]
version 3.2021.04.24, in Full Batch Mode, if you have a batch downloading in process, then you adjust the app's window size, or adjust the size of table columns, the app will starts blinking and will not stop even when you switch to the other tabs like the Log tab.

Also, if the window size and column sizes have been adjusted before starting the batches, it will also blink but not as hard.

Here's the video:
https://www.youtube.com/watch?v=fQqZV9E9byI

**Comment by Nandaka** [comment]
should be fixed in 2fd7156e1a8ae9db5aacca80b755eeeb93984877, I will update in new release

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/DanbooruDownloader/releases/tag/v3.20211104
