### ISSUE TITLE
Virus warning on v3.20211104

### ISSUE THREAD

**Issue by matsumotokenji** [Nandaka/DanbooruDownloader#253]
welp, after latest AV update i got this

![image](https://user-images.githubusercontent.com/22205034/140610877-b2361e48-26ee-4af9-83b9-fa04ae070838.png)
![image](https://user-images.githubusercontent.com/22205034/140610906-f49915f3-f429-45be-991a-a8cac8ab3b30.png)

**Comment by Nandaka** [comment]
most likely false positive? https://www.virustotal.com/gui/file/c827693601bf997811ee0e35e3964e93e8611408ee1ba9a957e2d53cf208068c?nocache=1

![image](https://user-images.githubusercontent.com/836867/140611123-c7b4b3c7-5a30-45ee-b9df-150fdda09942.png)

**Comment by matsumotokenji** [comment]
hmm... probably.
