### ISSUE TITLE
Incorrectly skipped image/video without logs.

### ISSUE THREAD

**Issue by matsumotokenji** [Nandaka/DanbooruDownloader#254]
when i do batch download from sankaku complex occasionally i get skipped imge without logs so i decided to dig in when i encounter this when batch downloading a relatively small image count tag.

When i try to batch download
https://chan.sankakucomplex.com/cn/?tags=natetheknife

I discovered these 2 object is not downloaded via manual lookup (no logs can be found)
25010400
25079791

When i try to manually downlaod from Main -> down load list i get this error message
No valid file_url, probably deleted.

![image](https://user-images.githubusercontent.com/22205034/143425547-4ef00d6b-119f-44f8-8677-41b271be3f49.png)

wonder if this might be a bug that cause DanbooruDownloader failed to get the URL? (even it is printed out correctly like the above image. lol)

I can manually download the file from thr website directly without issue.

Thanks.

**Comment by Nandaka** [comment]
might need to update the cookie values for sankaku? looks ok in my side.
![image](https://user-images.githubusercontent.com/836867/143460076-ee203072-96ea-4b21-802d-115c2e845f93.png)

**Comment by matsumotokenji** [comment]
My cookie, anything wrong?
![image](https://user-images.githubusercontent.com/22205034/143475990-ccee0405-9190-4072-94b1-0b846a493e2d.png)

**Comment by matsumotokenji** [comment]
I copied the latest cookie string from header request, same issue.

**Comment by Nandaka** [comment]
Ensure the user agent also the same as the browser that you use.
![image](https://user-images.githubusercontent.com/836867/143535795-696cc063-5f5c-4348-8914-8dfef99151e4.png)

You can verify if the cookie is accepted by searching page 26++ in sankaku. Below is the error if you are not authenticated. 
![image](https://user-images.githubusercontent.com/836867/143535917-fb6730e6-1b1f-40ba-85d6-2ad3b40cc1f8.png)

**Comment by matsumotokenji** [comment]
Yes, using the correct user agents

I can go to page up to 50

I found it strange, previously i can go beyond page 51 before an version update. Now only up to page 50 and i get page not found error with latest version.

**Comment by Nandaka** [comment]
looks ok for me.
![image](https://user-images.githubusercontent.com/836867/143548272-1c4e067e-727b-4d37-96dc-7a5da6f7a6f1.png)

my level is a contributor though.
![image](https://user-images.githubusercontent.com/836867/143548346-62f9e18b-cb0d-48b2-ac45-02a7f5c8406d.png)

**Comment by matsumotokenji** [comment]
I tried my best to re-setup step by step from readme and still can't find any solution.
the most painful part is files skipped without any logs.

**Comment by matsumotokenji** [comment]
ok found the cause, 

1. skipped image/video without logs - image id existed in the DB. Need to uncheck skip if exist in DB.
![image](https://user-images.githubusercontent.com/22205034/143870105-cb45ea43-a3eb-4832-8d45-11ccbbc7c54b.png)

2. Page 51 issue.
Below full error logs, can't figure this out.  I remember previously DanbooruDownloader will inject the next=123456 url tag but for my case it did't. Not major issue but, Hope can find a solution.
logs:
[DoBatchJob] Downloading list: https://chan.sankakucomplex.com/?tags=samneco&page=51
[DoBatchJob] Error Getting List (1 of 5): The remote server returned an error: (404) Not Found. Wait for 60s.
[DoBatchJob] Retrying...
[DoBatchJob] Error Getting List (2 of 5): The remote server returned an error: (404) Not Found. Wait for 60s.
[DoBatchJob] Retrying...
[DoBatchJob] Error Getting List (3 of 5): The remote server returned an error: (404) Not Found. Wait for 60s.
[DoBatchJob] Retrying...
[DoBatchJob] Error Getting List (4 of 5): The remote server returned an error: (404) Not Found. Wait for 60s.
[DoBatchJob] Retrying...
[DoBatchJob] Error Getting List (5 of 5): The remote server returned an error: (404) Not Found. Wait for 60s.
[DoBatchJob] Retrying...
[DoBatchJob] Cannot load list

case close for issue no.1 is solved.
