### ISSUE TITLE
Adding Sankaku results to download list gives error "Input string was not in a correct format"

### ISSUE THREAD

**Issue by jubuttib** [Nandaka/DanbooruDownloader#270]
Version: 3.2022.08.04

Problem:
Trying to add any result from Sankaku to the download list causes the error "Input string was not in a correct format".

Cookie value was added to profile as per instructions, and searches work perfectly fine.

Error text:

<details>
<summary>Details</summary>
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at DanbooruDownloader3.Engine.SankakuComplexParser.ReparseTags(DanbooruPost post, HtmlDocument doc) in D:\UserData\Dropbox\DanbooruDownloader3\DanbooruDownloader3\DanbooruDownloader3\Engine\SankakuComplexParser.cs:line 185
   at DanbooruDownloader3.Engine.SankakuComplexParser.ParsePost(DanbooruPost post, String postHtml, Boolean overideTagParsing) in D:\UserData\Dropbox\DanbooruDownloader3\DanbooruDownloader3\DanbooruDownloader3\Engine\SankakuComplexParser.cs:line 120
   at DanbooruDownloader3.FormMain._clientPost_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e) in D:\UserData\Dropbox\DanbooruDownloader3\DanbooruDownloader3\DanbooruDownloader3\FormMain.cs:line 315
   at System.Net.WebClient.OnDownloadStringCompleted(DownloadStringCompletedEventArgs e)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
DanbooruDownloader3
    Assembly Version: 3.2022.8.4
    Win32 Version: 3.2022.08.04
    CodeBase: file:///B:/Manga%20ja%20Sarjikset/Hentai/Danbooru%20Downloader/DanbooruDownloader3.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
DanbooruDBProvider
    Assembly Version: 1.2020.6.14
    Win32 Version: 1.2020.06.14
    CodeBase: file:///B:/Manga%20ja%20Sarjikset/Hentai/Danbooru%20Downloader/DanbooruDBProvider.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
log4net
    Assembly Version: 1.2.11.0
    Win32 Version: 1.2.11.0
    CodeBase: file:///B:/Manga%20ja%20Sarjikset/Hentai/Danbooru%20Downloader/log4net.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data.SQLite
    Assembly Version: 1.0.113.0
    Win32 Version: 1.0.113.0
    CodeBase: file:///B:/Manga%20ja%20Sarjikset/Hentai/Danbooru%20Downloader/System.Data.SQLite.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4536.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4494.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
HtmlAgilityPack
    Assembly Version: 1.4.6.0
    Win32 Version: 1.4.6.0
    CodeBase: file:///B:/Manga%20ja%20Sarjikset/Hentai/Danbooru%20Downloader/HtmlAgilityPack.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
</details>

**Comment by Nandaka** [comment]
weird, it works ok when I tried it. Does it able to resolve the file url? Do you have the post id?

![image](https://user-images.githubusercontent.com/836867/182980503-279f6171-6a1e-4018-8617-8a8a61d3683f.png)

**Comment by Romangelo** [comment]
Same for me. Preview images not showing, no url. If try to add it to the download tab, it crashes

![Same](https://user-images.githubusercontent.com/25454806/183236291-54eaf7b2-8516-433b-a37e-abf5e89266f5.png)

**Comment by Nandaka** [comment]
> preview

You need to tick the `Load Preview` check box.

Also, it should create dump page in the application folder with filename `Dump for Post xxx`. Can you upload it here.

**Comment by Romangelo** [comment]
https://github.com/Nandaka/DanbooruDownloader/issues/268#issuecomment-1207185520

**Comment by Nandaka** [comment]
@jubuttib can try https://github.com/Nandaka/DanbooruDownloader/releases/tag/v3.20220806 ?

**Comment by jubuttib** [comment]
> @jubuttib can try [`v3.20220806` (release)](https://github.com/Nandaka/DanbooruDownloader/releases/tag/v3.20220806) ?

About to try, quick question though: Is it best practice to backup old installation, then just extract the archive over the old, or to delete everything before extracting?

**Comment by Nandaka** [comment]
better backup first. if there is no issues then you can just delete the old files.

**Comment by jubuttib** [comment]
> better backup first. if there is no issues then you can just delete the old files.
> 
> 1. zip the old files as backup
> 2. then you overwrite with the new files.
> 3. delete the backup zip if there is no issue

OK, so no need to delete the old folder before extracting, gotcha.

New problem right now though with the latest version: It worked for a while, was able to go through about 10 pages on Sankaku, but now whenever I hit "get" to do a search on any source (or at least Sankaku, danbooru and gelbooru), I get a "Save As" prompt for the search .xml file... Will faff around with this for a bit, and if it persists I'll make a new issue (should I not find it)

**Comment by Nandaka** [comment]
untick `Save Query` in main tab?
![image](https://user-images.githubusercontent.com/836867/183403815-e0916ccb-429a-4a95-a6a1-1e52204aa339.png)

also my setting for reference
![image](https://user-images.githubusercontent.com/836867/183403897-8c64f2c6-15dd-41a1-aec0-9b64844caa9d.png)

**Comment by jubuttib** [comment]
Ah, so that's what that did... I was foolish and assumed it saved it for the next time I launch the program...
