### ISSUE TITLE
Sankaku Batch Job can't go past page 25 despite beeing logged in via Cookie

### ISSUE THREAD

**Issue by MaximalDis** [Nandaka/DanbooruDownloader#271]
Using most recent release v3.20220804 the batch job for Sankaku stops at page 25, Error 404.

I am logged in via cookie, and it has been working in the past with older versions. I am able to see/download images for which an account would be needed.

Might still be a problem with recent changes on Sankaku side.

**Comment by Nandaka** [comment]
ensure the cookie and useragent match.

https://github.com/Nandaka/DanbooruDownloader/issues/268#issuecomment-1206165965

Looks fine in my pc
![image](https://user-images.githubusercontent.com/836867/183228477-58d04a53-23ab-4616-b9b1-f45d50910149.png)

**Comment by MaximalDis** [comment]
Used a fresh extract of the downloader.

Added cookie and useragent from the same browser (Google Chrome):

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`

Sadly it still wouldn't let me pass page 25. I made sure to change `&` into `&amp;` for blacklist tags in cookie.

Other than that it works fine though. I'll get around that using more specific tags. Thank you for your help and hard work!

**Comment by Nandaka** [comment]
sorry about that, you can try to use the date range e.g. `date:2022-08-01..2022-08-08` in the search tags

**Comment by Romangelo** [comment]
Even with my account logged in on browser, I can't browse page 26 or higher.

https://chan.sankakucomplex.com/?tags=dikko&page=26

"Error: You can only view up to 50 pages of results this way - get Sankaku Plus to see more!"

It says 50 pages, but I can't even browse page 26. There might be a bug on their site, or they just decreased the page cap for free users.

For now, just need to use date range trick, and split each batch into 500 files.
