### ISSUE TITLE
sankakucomplex "AI banner" bug

### ISSUE THREAD

**Issue by matsumotokenji** [Nandaka/DanbooruDownloader#279]
The new "Create your own art with AI now!" banner is messing up with search and full batch download
e.g.
![image](https://user-images.githubusercontent.com/22205034/229948016-41f92d1a-133d-4325-accc-a7fe2d65b2f3.png)

searches will always list the images from the banner 
![image](https://user-images.githubusercontent.com/22205034/229948408-7746ecb9-3771-4a2d-acf0-ad695b7f50e3.png)

And full batch download will always download it
![image](https://user-images.githubusercontent.com/22205034/229948677-eddda1f9-d675-4253-a418-54f8859eccd2.png)

and doing full batch download with tags like yamayoshi_tanosuke
will return below error:
************** Exception Text **************
System.ArgumentOutOfRangeException: Value of '-3' is not valid for 'Maximum'. 'Maximum' must be greater than or equal to 0.
Parameter name: Maximum
   at System.Windows.Forms.ProgressBar.set_Maximum(Int32 value)
   at DanbooruDownloader3.FormMain.UpdateUi(Int32 current, Int32 total)

Anyone else got issue with it?

**Comment by bea831333** [comment]
@Nandaka untested fix here https://github.com/Nandaka/DanbooruDownloader/pull/280

**Comment by bea831333** [comment]
@Nandaka and something that uses correct syntax https://github.com/Nandaka/DanbooruDownloader/pull/281. Yea don't trust random pull requests

**Comment by Romangelo** [comment]
@Nandaka Can you please also take a look at this issue?

https://github.com/Nandaka/DanbooruDownloader/issues/277

**Comment by matsumotokenji** [comment]
@Nandaka @bea831333 
hi, thanks for the update, i just noticed there is a bug,
![image](https://github.com/Nandaka/DanbooruDownloader/assets/22205034/40145358-0a3e-42ad-89c4-864a72f9ef8f)

on tags search with only 1 page, e.g. 18 object, even the program detects 18 actual+10 AI banner object, it will only process the first 18 object and ignore the rest.
