### ISSUE TITLE
Sankaku no longer work

### ISSUE THREAD

**Issue by Romangelo** [Nandaka/DanbooruDownloader#283]
Both full batch mode and normal mode.

Also, %uploadDateTime% doesn't work on Sankaku (always get 0001-01-01 00_00_00 for all files)

Log for full batch mode:
[DoBatchJob] Getting file_url from https://chan.sankakucomplex.com/post/show/adfef968d293259d63c1f454f79000f7
[DoBatchJob] Error Resolving FileUrl (1 of 2): Object reference not set to an instance of an object. ==> Wait for 30s.
[DoBatchJob] Retrying...
[DoBatchJob] Error Resolving FileUrl (2 of 2): Object reference not set to an instance of an object. ==> Wait for 30s.
[DoBatchJob] Retrying...
[DoBatchJob] Download skipped, ID: 33544833 ==> No file_url, probably deleted

For normal mode, it can't get the URLs.

**Comment by jkaryan** [comment]
Same issue here.

**Comment by bea831333** [comment]
there was a website redesign. usually just a matter of updating the parser after noticing which parts moved where. I'll look into it later

**Comment by Nandaka** [comment]
will upload the exe later on, please check on releases tab
