### ISSUE TITLE
Where do i run?

### ISSUE THREAD

**Issue by galaxdoshaming** [Nandaka/DanbooruDownloader#301]
I'm a little confuse, where is the executable file so that i can run it?
![image](https://github.com/user-attachments/assets/9373dcf9-074b-48d2-8a4d-ab8db48df61d)
![image](https://github.com/user-attachments/assets/892a33d9-c13b-4924-b458-3de2d39ac7e4)

**Comment by wind-02** [comment]
you can download from the release page, https://github.com/Nandaka/DanbooruDownloader/releases
