### ISSUE TITLE
Whitelist for Filename Tags

### ISSUE THREAD

**Issue by TarouMaso** [Nandaka/DanbooruDownloader#46]
A whitelist for tags would be good, so that certain tags are always in the filename. For example a picture has too many tags and so the filename will always be cutted: 1girl blue_hair aqua_eyes foresh.jpg but if we have foreshortening in the whitelist so name would be: 1girl blue_hair foreshortening aqua_e.jpg so danbooru downloader would just cut tags which are not on the whitelist. Instead of the ones which someone wants to keep. Excuse my bad english.

**Comment by Nandaka** [comment]
usage:
1. Create ```included_tags.txt``` file in the app folder.
2. Separate each tags with new line.
3. The generated filename will prioritize the tags inside ```included_tags.txt```
