### ISSUE TITLE
Partial filenames when using %originalFilename% tag

### ISSUE THREAD

**Issue by Zumochi** [Nandaka/DanbooruDownloader#54]
In Full Batch Mode, if I use the tag %originalFilename% in Save Folder as the filename, the filename gets trimmed to the last X amount of characters (changes with provider).

**Comment by Nandaka** [comment]
This is due to windows path+filename length limitation (I think around
250?). Check the Settings Tab to control the length (hardlimit to 250chars)

On Wed, Jan 7, 2015 at 12:56 AM, Zumochi <notifications@github.com> wrote:

> In Full Batch Mode, if I use the tag %originalFilename% in Save Folder as
> the filename, the filename gets trimmed to the last X amount of characters
> (changes with provider).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Nandaka/DanbooruDownloader/issues/54>.
>



-- 
My Blog at http://nandaka.wordpress.com
