### ISSUE TITLE
Enhancement: Last Tag Page Identifier to aid in updating tags

### ISSUE THREAD

**Issue by DarkPulse** [Nandaka/DanbooruDownloader#56]
Not really sure if this is even doable or not, but sooner or later, we all have to update our tags.

The problem is basically that not only can it be a very time-consuming process (12,000+ pages on Sankaku Complex alone!), but there's also no way we know which ones we actually "need" and which ones are already present.

Would it be possible for the Downloader to "read" the tags XML files and know which entry is the last page in the file, so that we know exactly on which page we should resume the tag updating from? Looking in the XMLs, it does give each tag an ID, so this should be (in theory) possible, though I don't know if it is possible in practice at all.

**Comment by Nandaka** [comment]
I don't think possible, as the id in sankaku complex is not exposed, so I'm
using running number to fill it.
Also the web ui doesn't have the option to sort by id, only by
date/name/etc.

**Comment by Nandaka** [comment]
Should not be required anymore, as the application will try to parse the tags details in the image post page.

Requirement: ```Use Global Tags.xml``` must be un-tick in the Settings tab.
![image](https://cloud.githubusercontent.com/assets/836867/22455327/b287abc4-e7c6-11e6-89dc-a68317000ceb.png)
