### ISSUE TITLE
Tagging limits

### ISSUE THREAD

**Issue by Corbamis** [Nandaka/DanbooruDownloader#57]
Hi, i just tried to limit the number of tags used for creating path, with format like this to get pics well sorted :
*%copyright%\_%artist%\@%character%\%md5%*

In config, if i use 1 as limit for copyright and character, it wont work, still getting all copyrights and characters name, and for artists, with limit 1, i get "multiple_artists" as folder name.

Error, or i'm getting it wrong for this option?
Thanks for helping.

**Comment by Nandaka** [comment]
any sample I can use? and for which board.

**Comment by Corbamis** [comment]
Tag *fate_testarossa* on Gelbooru, with previous format and a limit of 1, in full batch job give me : 

*lyrical_nanoha mahou_shoujo_lyrical_nanoha\_multiple_artists\@bardiche fate_testarossa raising_heart takamachi_nanoha\07dfa11131a1e4d5a01f6bc229b7c668.png*

for one of the first pics as sample.

Same for Danbooru, on full batch mod, limit to 1 copyright, 1 artist, 1 char, it gives me all copyright, all chars, and "multiple_artists" instead of the name of first one.

Btw, thanks for quick answering!

**Comment by Nandaka** [comment]
> "multiple_artists" 

this is the default behaviour if the artist counts exceed the limit.

by right, the other tags should also have the same behaviour (e.g. multiple_copyrights, multiple_character, etc), but it got some bugs inside :smile:

**Comment by Corbamis** [comment]
Any hint to successfully get only 1 copyright, 1 char, 1 artist at the end? :p

**Comment by Nandaka** [comment]
in ascending order? maybe :smile:

**Comment by Nandaka** [comment]
see https://nandaka.wordpress.com/2015/04/29/danbooru-downloader-201501429/

**Comment by Corbamis** [comment]
Thanks, working like a charm.
