### ISSUE TITLE
add support for rule34hentai.net ?

### ISSUE THREAD

**Issue by AreFinstad** [Nandaka/DanbooruDownloader#60]
add support for http://rule34hentai.net/ ?
i cant for the life of me get http://rule34hentai.net/ working with your program. 
its using Shimmie version 2.5.4 

could anyone help me set that site up in your program? or update the program with an added profile.

**Comment by Nandaka** [comment]
you can edit the DanbooruProviderList.xml using notepad and paste below text using notepad.

```XML
  <DanbooruProvider>
    <Name>http://rule34hentai.net/</Name>
    <DefaultLimit>0</DefaultLimit>
    <HardLimit>0</HardLimit>
    <Preferred>Xml</Preferred>
    <QueryStringXml>/index.php?q=/rss/images/%_query%</QueryStringXml>
    <QueryStringJson />
    <QueryStringHtml />
    <Url>http://rule34hentai.net/</Url>
    <UserName />
    <Password />
    <LoginType>Anonymous</LoginType>
    <PasswordSalt />
    <PasswordHash />
    <BoardType>Shimmie2</BoardType>
    <TagDownloadUseLoop>false</TagDownloadUseLoop>
  </DanbooruProvider>
```

![image](https://cloud.githubusercontent.com/assets/836867/19019498/efdcacc2-88bc-11e6-9ace-a179f71cabcd.png)

some tags/keyword might not be supported because invalid xml entities (the e in pokemon)
