### ISSUE TITLE
Image Size selection doesn't have effect between runs if it's Thumbnail

### ISSUE THREAD

**Issue by JMM72** [Nandaka/DanbooruDownloader#62]
In Settings -> Download -> Image Size, if the selection is "Thumbnail", next time you open the program the setting still says "Thumbnail", however when downloading any image, it does not get the thumbnail size.

Steps to reproduce:
1. Go to Settings -> Download -> Image Size, select "Thumbnail", press "Save" button.
2. Go to Main, do any search, add any image to the download list, and download it; the image is of thumbnail size.
3. Close DannbooruDownloader and reopen it.
4. Go to Settings -> Download -> Image Size. The setting is still at "Thumb".
5. Go to Main, do any search, add any image to the download list, and download it; the image is not of thumbnail size, but of full size (probably).

If you go Settings -> Download -> Image Size, select any other image size, and then select "Thumb" again, the images will download again of Thumb size, but the setting doesn't have effect between runs.

**Comment by JMM72** [comment]
Apparently when loading the settings file, the loaded value changes the control in the Settings panel; however it doesn't affect the global variable. The global variable for the download size only changes when you actually select something different in the actual control.

**Comment by Nandaka** [comment]
Try https://github.com/Nandaka/DanbooruDownloader/releases/tag/v3.20151012

**Comment by JMM72** [comment]
Solved, thanks.
