### ISSUE TITLE
Gelbooru parser broken?

### ISSUE THREAD

**Issue by Liandriz** [Nandaka/DanbooruDownloader#65]
Hi, in full batch mode, seems like Gelbooru parser is down? Log are full of C# errors, any help?

**Comment by Nandaka** [comment]
Gelbooru blocked the API access, so it won't work for now.

**Comment by Nandaka** [comment]
Manual work around for login:
1. Login to gelbooru using your browser.
2. Copy the cookie value for pass_hash and user_id.
![image](https://cloud.githubusercontent.com/assets/836867/11134671/9949b130-89d9-11e5-9731-5759774fb747.png)
3. Change the method for gelbooru to html.
![image](https://cloud.githubusercontent.com/assets/836867/11134710/e27733aa-89d9-11e5-9289-68e43013d8a3.png)
4. do one search at gelbooru, it should fail.
5. update the cookie name&value in settings
![image](https://cloud.githubusercontent.com/assets/836867/11134759/3fd703cc-89da-11e5-826f-103df6515030.png)
6. do another search, it should fail again.
7. add the 2nd cookie name and value.
8 Change the method for gelbooru back to xml.

It should work.
