### ISSUE TITLE
Folder Creation

### ISSUE THREAD

**Issue by Liandriz** [Nandaka/DanbooruDownloader#66]
For batch download, if you use some blacklist tags, and custom filename format, DD creates folders before checking for blacklist or not, so it happens to get a lot of empty folders.
Is it possible to check tags before creating folders?

**Comment by Nandaka** [comment]
by right it should not download the blacklisted tag for batch download. Only ignored tag will be removed from the filename.

**Comment by Liandriz** [comment]
Yes, image not downloaded but folder created.
Try to blacklist league_of_legends, and then batch download league_of_legends with %copyright%\@\%artist%\%md5% filename : all folders created, but no files downloaded.
