### ISSUE TITLE
Sankaku Tags

### ISSUE THREAD

**Issue by Liandriz** [Nandaka/DanbooruDownloader#67]
Seems Sankaku is returning tags without the "_", with spaces instead.
All other boorus return tags with "_", so can a option be made to replace spaces with "_" to do not have duplicates, some with "_" and others with spaces?

**Comment by Nandaka** [comment]
can you give some samples?

**Comment by Liandriz** [comment]
Using Sankaku HTTPS, with auth (cause no auth seems to limit to 2k results), for the search "league_of_legends", with "%copyright%\@\%artist%\%md5%" as folder, it gives me  : "league of legends\@\torahime (roland00)" when Danbooru returns "league_of_legends\@\torahime_(roland00)" for same image, so getting lot of duplicates.

**Comment by Nandaka** [comment]
so you want to replace underscore with space?

**Comment by Liandriz** [comment]
Would be great to have homoeneous naming to avoid duplicates yes.
if you can normalize tags, with underscore or space, it would be great (maybe checkbox in option to choose to force to use space or underscore for all tags?).

Btw, thanks another time for the support.
