### ISSUE TITLE
can't download from gelbooru

### ISSUE THREAD

**Issue by Owyn** [Nandaka/DanbooruDownloader#69]
Tried old version - failed, got newest one - same result:

tried full batch mode, only errors:

[DoBatchJob] Processing Batch Job#0
[DoBatchJob] Downloading list: http://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=shio_(shia-ushio)&limit=100
[DoBatchJob] Error: Недопустимые данные на корневом уровне., строка 1, позиция 1.
Stack Trace: 
   в System.Xml.XmlTextReaderImpl.Throw(Exception e)
   в System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   в System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   в DanbooruDownloader3.DAO.DanbooruPostDao.ProcessXML(String rawData)
   в DanbooruDownloader3.DAO.DanbooruPostDao..ctor(Stream input, DanbooruPostDaoOption option)
   в DanbooruDownloader3.FormMain.GetBatchImageList(String url, String query, DanbooruBatchJob job)
   в DanbooruDownloader3.FormMain.DoBatchJob(BindingList`1 batchJob)
Query: shio_(shia-ushio)
[DoBatchJob] Downloading list: http://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=shio_(shia-ushio)&limit=100&pid=1
[DoBatchJob] Error: Недопустимые данные на корневом уровне., строка 1, позиция 1.
Stack Trace: 
   в System.Xml.XmlTextReaderImpl.Throw(Exception e)
   в System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   в System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   в DanbooruDownloader3.DAO.DanbooruPostDao.ProcessXML(String rawData)
   в DanbooruDownloader3.DAO.DanbooruPostDao..ctor(Stream input, DanbooruPostDaoOption option)
   в DanbooruDownloader3.FormMain.GetBatchImageList(String url, String query, DanbooruBatchJob job)
   в DanbooruDownloader3.FormMain.DoBatchJob(BindingList`1 batchJob)
Query: shio_(shia-ushio)
[DoBatchJob] Downloading list: http://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=shio_(shia-ushio)&limit=100&pid=2
[DoBatchJob] Error: Недопустимые данные на корневом уровне., строка 1, позиция 1.
Stack Trace: 
   в System.Xml.XmlTextReaderImpl.Throw(Exception e)
   в System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   в System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   в DanbooruDownloader3.DAO.DanbooruPostDao.ProcessXML(String rawData)
   в DanbooruDownloader3.DAO.DanbooruPostDao..ctor(Stream input, DanbooruPostDaoOption option)
   в DanbooruDownloader3.FormMain.GetBatchImageList(String url, String query, DanbooruBatchJob job)
   в DanbooruDownloader3.FormMain.DoBatchJob(BindingList`1 batchJob)
Query: shio_(shia-ushio)
[DoBatchJob] Downloading list: http://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=shio_(shia-ushio)&limit=100&pid=3
[DoBatchJob] Error: Недопустимые данные на корневом уровне., строка 1, позиция 1.
Stack Trace: 
   в System.Xml.XmlTextReaderImpl.Throw(Exception e)
   в System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   в System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   в DanbooruDownloader3.DAO.DanbooruPostDao.ProcessXML(String rawData)
   в DanbooruDownloader3.DAO.DanbooruPostDao..ctor(Stream input, DanbooruPostDaoOption option)
   в DanbooruDownloader3.FormMain.GetBatchImageList(String url, String query, DanbooruBatchJob job)
   в DanbooruDownloader3.FormMain.DoBatchJob(BindingList`1 batchJob)
Query: shio_(shia-ushio)
[DoBatchJob] Downloading list: http://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=shio_(shia-ushio)&limit=100&pid=4
[DoBatchJob] Error: Недопустимые данные на корневом уровне., строка 1, позиция 1.
Stack Trace: 
   в System.Xml.XmlTextReaderImpl.Throw(Exception e)
   в System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   в System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   в DanbooruDownloader3.DAO.DanbooruPostDao.ProcessXML(String rawData)
   в DanbooruDownloader3.DAO.DanbooruPostDao..ctor(Stream input, DanbooruPostDaoOption option)
   в DanbooruDownloader3.FormMain.GetBatchImageList(String url, String query, DanbooruBatchJob job)
   в DanbooruDownloader3.FormMain.DoBatchJob(BindingList`1 batchJob)
Query: shio_(shia-ushio)
[DoBatchJob] Downloading list: http://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=shio_(shia-ushio)&limit=100&pid=5
[DoBatchJob] Error: Недопустимые данные на корневом уровне., строка 1, позиция 1.
Stack Trace: 
   в System.Xml.XmlTextReaderImpl.Throw(Exception e)
   в System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   в System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   в DanbooruDownloader3.DAO.DanbooruPostDao.ProcessXML(String rawData)
   в DanbooruDownloader3.DAO.DanbooruPostDao..ctor(Stream input, DanbooruPostDaoOption option)
   в DanbooruDownloader3.FormMain.GetBatchImageList(String url, String query, DanbooruBatchJob job)
   в DanbooruDownloader3.FormMain.DoBatchJob(BindingList`1 batchJob)
Query: shio_(shia-ushio)
[DoBatchJob] Downloading list: http://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=shio_(shia-ushio)&limit=100&pid=6
[DoBatchJob] Error: Недопустимые данные на корневом уровне., строка 1, позиция 1.
Stack Trace: 
   в System.Xml.XmlTextReaderImpl.Throw(Exception e)
   в System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   в System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   в DanbooruDownloader3.DAO.DanbooruPostDao.ProcessXML(String rawData)
   в DanbooruDownloader3.DAO.DanbooruPostDao..ctor(Stream input, DanbooruPostDaoOption option)
   в DanbooruDownloader3.FormMain.GetBatchImageList(String url, String query, DanbooruBatchJob job)
   в DanbooruDownloader3.FormMain.DoBatchJob(BindingList`1 batchJob)
Query: shio_(shia-ushio)
[DoBatchJob] Downloading list: http://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=shio_(shia-ushio)&limit=100&pid=7
[DoBatchJob] Error: Недопустимые данные на корневом уровне., строка 1, позиция 1.
Stack Trace: 
   в System.Xml.XmlTextReaderImpl.Throw(Exception e)
   в System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   в System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   в DanbooruDownloader3.DAO.DanbooruPostDao.ProcessXML(String rawData)
   в DanbooruDownloader3.DAO.DanbooruPostDao..ctor(Stream input, DanbooruPostDaoOption option)
   в DanbooruDownloader3.FormMain.GetBatchImageList(String url, String query, DanbooruBatchJob job)
   в DanbooruDownloader3.FormMain.DoBatchJob(BindingList`1 batchJob)
Query: shio_(shia-ushio)
[DoBatchJob] Downloading list: http://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=shio_(shia-ushio)&limit=100&pid=8
[DoBatchJob] Error: Недопустимые данные на корневом уровне., строка 1, позиция 1.
Stack Trace: 
   в System.Xml.XmlTextReaderImpl.Throw(Exception e)
   в System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   в System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   в DanbooruDownloader3.DAO.DanbooruPostDao.ProcessXML(String rawData)
   в DanbooruDownloader3.DAO.DanbooruPostDao..ctor(Stream input, DanbooruPostDaoOption option)
   в DanbooruDownloader3.FormMain.GetBatchImageList(String url, String query, DanbooruBatchJob job)
   в DanbooruDownloader3.FormMain.DoBatchJob(BindingList`1 batchJob)
Query: shio_(shia-ushio)
[DoBatchJob] Downloading list: http://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=shio_(shia-ushio)&limit=100&pid=9
[DoBatchJob] Error: Недопустимые данные на корневом уровне., строка 1, позиция 1.
Stack Trace: 
   в System.Xml.XmlTextReaderImpl.Throw(Exception e)
   в System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   в System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   в DanbooruDownloader3.DAO.DanbooruPostDao.ProcessXML(String rawData)
   в DanbooruDownloader3.DAO.DanbooruPostDao..ctor(Stream input, DanbooruPostDaoOption option)
   в DanbooruDownloader3.FormMain.GetBatchImageList(String url, String query, DanbooruBatchJob job)
   в DanbooruDownloader3.FormMain.DoBatchJob(BindingList`1 batchJob)
Query: shio_(shia-ushio)
[DoBatchJob] Downloading list: http://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=shio_(shia-ushio)&limit=100&pid=10
[DoBatchJob] Error: Недопустимые данные на корневом уровне., строка 1, позиция 1.
Stack Trace: 
   в System.Xml.XmlTextReaderImpl.Throw(Exception e)
   в System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   в System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   в DanbooruDownloader3.DAO.DanbooruPostDao.ProcessXML(String rawData)
   в DanbooruDownloader3.DAO.DanbooruPostDao..ctor(Stream input, DanbooruPostDaoOption option)
   в DanbooruDownloader3.FormMain.GetBatchImageList(String url, String query, DanbooruBatchJob job)
   в DanbooruDownloader3.FormMain.DoBatchJob(BindingList`1 batchJob)
Query: shio_(shia-ushio)
[DoBatchJob] Downloading list: http://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=shio_(shia-ushio)&limit=100&pid=11
[DoBatchJob] Error: Недопустимые данные на корневом уровне., строка 1, позиция 1.
Stack Trace: 
   в System.Xml.XmlTextReaderImpl.Throw(Exception e)
   в System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   в System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   в DanbooruDownloader3.DAO.DanbooruPostDao.ProcessXML(String rawData)
   в DanbooruDownloader3.DAO.DanbooruPostDao..ctor(Stream input, DanbooruPostDaoOption option)
   в DanbooruDownloader3.FormMain.GetBatchImageList(String url, String query, DanbooruBatchJob job)
   в DanbooruDownloader3.FormMain.DoBatchJob(BindingList`1 batchJob)
Query: shio_(shia-ushio)
[DoBatchJob] Downloading list: http://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=shio_(shia-ushio)&limit=100&pid=12
[DoBatchJob] Error: Недопустимые данные на корневом уровне., строка 1, позиция 1.
Stack Trace: 
   в System.Xml.XmlTextReaderImpl.Throw(Exception e)
   в System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   в System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   в DanbooruDownloader3.DAO.DanbooruPostDao.ProcessXML(String rawData)
   в DanbooruDownloader3.DAO.DanbooruPostDao..ctor(Stream input, DanbooruPostDaoOption option)
   в DanbooruDownloader3.FormMain.GetBatchImageList(String url, String query, DanbooruBatchJob job)
   в DanbooruDownloader3.FormMain.DoBatchJob(BindingList`1 batchJob)
Query: shio_(shia-ushio)
[DoBatchJob] Downloading list: http://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=shio_(shia-ushio)&limit=100&pid=13
[DoBatchJob] Error: Недопустимые данные на корневом уровне., строка 1, позиция 1.
Stack Trace: 
   в System.Xml.XmlTextReaderImpl.Throw(Exception e)
   в System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   в System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   в DanbooruDownloader3.DAO.DanbooruPostDao.ProcessXML(String rawData)
   в DanbooruDownloader3.DAO.DanbooruPostDao..ctor(Stream input, DanbooruPostDaoOption option)
   в DanbooruDownloader3.FormMain.GetBatchImageList(String url, String query, DanbooruBatchJob job)
   в DanbooruDownloader3.FormMain.DoBatchJob(BindingList`1 batchJob)

**Comment by Nandaka** [comment]
Have you key in your cookie information?

**Comment by Owyn** [comment]
I think not, but links from the log doesn't open in the browser either, just says     
    <posts count="65" offset="0"/>

Do I need a key to download anything now? I remember it was always fine even without it

**Comment by Nandaka** [comment]
now they require login to be able to use the API, so now you need to login to the browser and copy the cookie value. Please follow the instruction on the blog: https://nandaka.wordpress.com/
