### ISSUE TITLE
Unable to download from e621.net

### ISSUE THREAD

**Issue by modicon** [Nandaka/DanbooruDownloader#72]
Server returns error 500: Internal Server Error when trying get file_url.

Possible index.xml file format was changed.

**Comment by Nandaka** [comment]
they changed the xml format.

Their format is not really the old danbooru api (http://danbooru.donmai.us/post/index.xml) or the new one (http://danbooru.donmai.us/posts.xml)

**Comment by Nandaka** [comment]
Change the Preferred API to JSON, it should do the trick.

1. Select the Provider.
2. Click the Edit button.
3. Change the 'Preferred' to JSON.
![image](https://cloud.githubusercontent.com/assets/836867/12937203/2f5621c0-cfe1-11e5-835c-b89484cfabd8.png)
4. Click Save, then OK.

it should fix the issue.
