### ISSUE TITLE
cant download images by tag

### ISSUE THREAD

**Issue by youbaka** [Nandaka/DanbooruDownloader#73]
which tags i need i cant understand 
![2016-02-08 18 38 45](https://cloud.githubusercontent.com/assets/9166849/12892989/bd60d89a-ce9f-11e5-8220-daf4c59957e3.png)

**Comment by Nandaka** [comment]
From readme.txt

A. Getting tags.xml:
1. Download tags.xml from Settings tab => Click update tags.xml
2. Select the provider from the URL combo box then press download, I recommend to use yande.re.
3. Wait until the download complete.
