### ISSUE TITLE
Sankaku Complex 

### ISSUE THREAD

**Issue by FreakyGamer** [Nandaka/DanbooruDownloader#74]
Every time when i donwload in the full batch mode from Sankaku Complex the Name goes red in the list.

LOG: 

[DoBatchJob] Error Getting List (1 of 5): Der Remoteserver hat einen Fehler zurückgegeben: (429) Too many requests - please slow down.... Wait for 60s.
[DoBatchJob] Retrying...
[DoBatchJob] Error Getting List (2 of 5): Der Remoteserver hat einen Fehler zurückgegeben: (429) Too many requests - please slow down.... Wait for 60s.
[DoBatchJob] Retrying...
[DoBatchJob] Error Getting List (3 of 5): Der Remoteserver hat einen Fehler zurückgegeben: (429) Too many requests - please slow down.... Wait for 60s.
[DoBatchJob] Retrying...
[DoBatchJob] Error Getting List (4 of 5): Der Remoteserver hat einen Fehler zurückgegeben: (429) Too many requests - please slow down.... Wait for 60s.
[DoBatchJob] Retrying...
[DoBatchJob] Error Getting List (5 of 5): Der Remoteserver hat einen Fehler zurückgegeben: (429) Too many requests - please slow down.... Wait for 60s.
[DoBatchJob] Retrying...
[DoBatchJob] Cannot load list
[DoBatchJob] Batch Job #1: Done

Is that a problem that i can fix or is this normal ?

**Comment by Nandaka** [comment]
This is normal, as this is server side control. Just set some delays in the settings tab.

![image](https://cloud.githubusercontent.com/assets/836867/14226565/7eff4c82-f918-11e5-8ce5-09087a3e0885.png)
