### ISSUE TITLE
Request: add rule34.paheal.net

### ISSUE THREAD

**Issue by FreakyGamer** [Nandaka/DanbooruDownloader#75]
would it be possibel to add rule34.paheal.net to the download list ?

**Comment by Nandaka** [comment]
add this config on Form Provider (Click Edit -> Add button).
![image](https://cloud.githubusercontent.com/assets/836867/14319982/e9269f4a-fc45-11e5-8483-a29e5f9504bc.png)

or download the provider xml: https://github.com/Nandaka/DanbooruDownloader/blob/master/DanbooruDownloader3/DanbooruProviderList.xml

Remember to backup your file.

**Comment by Kikoshi** [comment]
Hello, 
With the provider file.. The program doesn't start :<

**Comment by Nandaka** [comment]
what is the error message? Ensure you are using the latest version. I just tested it and it is working.

Also, click the raw button to get the file, or save it from here: https://raw.githubusercontent.com/Nandaka/DanbooruDownloader/master/DanbooruDownloader3/DanbooruProviderList.xml
