### ISSUE TITLE
danbooru downloader stop working for sankaku complex

### ISSUE THREAD

**Issue by naruhina2016** [Nandaka/DanbooruDownloader#77]
well as the title says all,
whenever i try to download tags from sankaku complex 
danbooru automatically stop working.
please tell what to do to fix this problem?

**Comment by Nandaka** [comment]
most likely they change the layout for the tag page. I don't recommend to download tags xml from sankaku, as it will take thousands pages.

**Comment by naruhina2016** [comment]
but now i have another problem i was trying to download love live school idol project images from sankaku complex via but after 999 download it notified me that the batch is done which is not true
and show it in red
![untitled](https://cloud.githubusercontent.com/assets/18094007/15635573/1a851db2-25e2-11e6-81dd-bb5a08afbe61.png)

i hope you can help me to fix my problem

**Comment by Wassaaaa** [comment]
You need to add your account, there's a limit for non-registered users in sankaku

**Comment by naruhina2016** [comment]
how can i add my account?

**Comment by Wassaaaa** [comment]
On the main tab go to Edit, choose Sankaku Complex as provider, fill UserName and Password and choose UserPass as LoginType

**Comment by Nandaka** [comment]
@naruhina2016 : check the readme regarding sankaku login

**Comment by naruhina2016** [comment]
it still gives me the same thing and where can i find sankaku login on readme?

**Comment by Nandaka** [comment]
Q7: How to login to Gelbooru/Sankaku/get cookie value?
A7: Follow this step:
    1. Press F12 on your Chrome browser and select Network tab.
    2. Go to the booru site and login.
    3. Click one of the entry and copy the Cookie value from the Request Header. 
       For gelbooru, it should like this: user_id=<number>; pass_hash=<long string>
       For sankaku, login=<username>; pass_hash=<long string>;
    4. Paste the Cookie value to the Username field.
    5. Set Login Type to Cookie.
    6. Set Use Auth to True. Refer to http://i.imgur.com/rCCjnPs.png

**Comment by naruhina2016** [comment]
which one is auth?

**Comment by Nandaka** [comment]
>> For sankaku, login=username; pass_hash=something;

or just copy the whole cookies and paste it to the box like in here: http://i.imgur.com/rCCjnPs.png

**Comment by naruhina2016** [comment]
but still which one is auth?

**Comment by Nandaka** [comment]
My mistake, remove the last line.

Q7: How to login to Gelbooru/Sankaku/get cookie value?
A7: Follow this step:
    1. Press F12 on your Chrome browser and select Network tab.
    2. Go to the booru site and login.
    3. Click one of the entry and copy the Cookie value from the Request Header. 
       For gelbooru, it should like this: user_id=<number>; pass_hash=<long string>
       For sankaku, login=<username>; pass_hash=<long string>;
    4. Paste the Cookie value to the Username field.
    5. Set Login Type to Cookie. Refer to http://i.imgur.com/rCCjnPs.png

**Comment by naruhina2016** [comment]
but where can i find auth?

**Comment by Nandaka** [comment]
No more auth, just get the cookie (read answer above).

**Comment by naruhina2016** [comment]
sorry for the late late reply but no matter what i do it doesn't work..:(
i've copied the whole login cookie for sankaku but nothing happens?

**Comment by Nandaka** [comment]
can you show me your config for the provider?

**Comment by naruhina2016** [comment]
unfortunately i cant get any access to the config of sankaku complex it gave me an error

**Comment by naruhina2016** [comment]
![untitled](https://cloud.githubusercontent.com/assets/18094007/17221200/1efb86e8-54f3-11e6-979e-530fb122ca95.png)

well here you go mate

**Comment by Nandaka** [comment]
well, that's your problem, you didn;t select the login type and fill in the cookie.
![image](https://cloud.githubusercontent.com/assets/836867/17233075/551504b8-555f-11e6-986f-007814a46eb2.png)

**Comment by naruhina2016** [comment]
no the reason why didn't do it bcause i've download it again so thats why its blank but still
i've tried but it doesn't work

**Comment by Nandaka** [comment]
change http to https?

**Comment by naruhina2016** [comment]
yes it worked thanks...xD

**Comment by naruhina2016** [comment]
it worked but it didn't go quite well for sankaku complex i was trying to download animated gifs/videos it went well but after 9000+ it stopped download any further instead of being green when complete it went red like it was an error

**Comment by Nandaka** [comment]
There should be a log file in the application folder (e.g. log-2016-05-31.txt), can you check what is the error? I never download to 9000+ pages before, so I'm not sure what causing it. Also Sankaku use customized danbooru, so might have some weird behaviour.

**Comment by naruhina2016** [comment]
what do you mean customized danbooru?. and i have checked the log file but i cant seems to find the error that i was suppose to find!

**Comment by Nandaka** [comment]
sankaku danbooru doesn't follow the same standard with normal danbooru.

**Comment by naruhina2016** [comment]
aha i see so what can i do to download more pics from sankaku complex?

**Comment by Nandaka** [comment]
They limit to 1000 pages. If you open the page, it will return: 

> Error: You can only view up to 1000 pages of results
