### ISSUE TITLE
Filename limit increase on the downloader with the new windows 10 NTFS long path option?

### ISSUE THREAD

**Issue by bugmenot2** [Nandaka/DanbooruDownloader#79]
Supposedly as of today, microsoft is releasing their windows 10 anniversary update as some may know. With this, microsoft is finally possibly enabling users the ability to up the file name limit past the default 260 character limit using the NTFS long path option. The downloader is already limited to under this limit to begin with, which cuts down on the name quite a bit.. especially if you're trying to name by tags. Would it be possible to perhaps add the ability to enable the client to go past this limit with a warning that makes it clear that "Do not use unless you are using windows 10 with NTFS long path enabled!", this way people have the option to at least if they maybe would like to store pictures with their full tag list on the name?

**Comment by Nandaka** [comment]
correct me if I'm wrong, but isn't this required .Net Framework 4.6.2?

Currenly I'm using .Net 4.0 to keep xp compatible.
