### ISSUE TITLE
tags .txt sidecar files?

### ISSUE THREAD

**Issue by AreFinstad** [Nandaka/DanbooruDownloader#80]
could we get support for text (.txt) sidecar files for the tags downloaded. 

all that needs too be done is have the filename and sidecar file be the same unique name and fill up the text with all the tags. one tag per line would be the best. 

this way you will add support for file and tag importing with the Hydrus client. ( https://github.com/hydrusnetwork/hydrus )

i and some of its users would love such a function as it would speed up our program aswell as a whole! :D 

tested the import around a bit, and it states that one tag per line is the way too go. and the file extension has too be part of the filename (or else it would collide with other formats tag files aswell.)

**Comment by Nandaka** [comment]
so 1 file, 1 tagfile? E.g someimages.jpg ==> someimages.jpg.txt?

Separate each tag by newline?

**Comment by Seedmanc** [comment]
So how to enable this? I'm not seeing any sidecars in the dl folder.
