### ISSUE TITLE
Request: New tag list for the inclusion of only specific tags in filenames.

### ISSUE THREAD

**Issue by Zangeon** [Nandaka/DanbooruDownloader#81]
Like I said on the blog, I'd like to request a new kind of list that works exactly opposite to how the "Ignored Tags" list works. Instead of being a list where only the tags _not_ on the list are included in filenames, it would be a list where only the tags _on_ the list are included, but only when the posts themselves use them as well.

**The way this would work would be like this**:
You would add a tag to the list, just like you would to the current Blackisted/Ignored Tags lists.
Then, when you perform a search/batch job for any tag, once a post gets fetched, the app checks to see if the post has any tags that match the ones on your list (just like it does for Ignored Tags).
Then, if you use %tags% in the filename format, the ones that match get added to the filename while the ones that don't will be ignored and not get added.

Such a list and the current "Ignored Tags" list would be mutually exclusive, and since the Settings tab is already quite full, in the effort to save space, maybe the current Ignored Tags list could be togglable in an "exclude only these / include only these" kind of way?

The reason I request this is because there's currently no way to have only certain tags be included in the filenames. %searchtag% doesn't take into consideration tags that you might want to have in the filenames, and if you add those tags to the search then every single file will have those tags in them even though they might not apply to the post itself. An example of this is searching for "~censored ~uncensored". The _vast_ majority of posts will only use one, but %searchtag% will add both to the filename regardless. %tags% also doesn't work as it will include any tag that isn't ignored. This means that the only way to achieve the same result as the suggested list is to ignore every single tag exept for the ones you want to have included in your filenames.

**Comment by Nandaka** [comment]
Duplicate with #46 ?
