### ISSUE TITLE
does this programm go over the 1,000th page of sankakucomplex?

### ISSUE THREAD

**Issue by arukom** [Nandaka/DanbooruDownloader#83]
ive had some imagegrabber before and they were all stuck at the 1,000th page of chan.sankakucomplex

does this downloader go past that?

**Comment by Nandaka** [comment]
> 1,000th page of chan.sankakucomplex

I think that is the limit set by sankakucomplex server?

**Comment by arukom** [comment]
had the problem with oder imagedownloaders, all of them dont go past that..

is there any way to get over it?

**Comment by Nandaka** [comment]
I don't think so. Sankaku return 'Error: You can only view up to 1000 pages of results' message even when I was logged in from browser.

You need to ask the board administrator.
