### ISSUE TITLE
Improperly named files.

### ISSUE THREAD

**Issue by Omallis** [Nandaka/DanbooruDownloader#84]
Hi, sorry I tried looking everywhere for an answer to this but couldn't find anything.  How can I get DanbooruDownloader to name the images I download from Danbooru properly like it would if I clicked download on the actual site. For example the file is properly named and tagged when downloaded from the site, but when I use %originalname% on boorudownloader the file name isn't quite right...
![untitled](https://cloud.githubusercontent.com/assets/22080325/18356650/a39b5d40-75bb-11e6-9fd5-4b8ef5b60e52.png)

**Comment by Nandaka** [comment]
Is it? The url I got from https://danbooru.donmai.us/posts/2479528 shows with underscore.

```
https://danbooru.donmai.us/data/__mimikyu_pokemon_pokemon_game_pokemon_sm_and_the_legend_of_zelda_drawn_by_lu_nya__ae12488a3cfbe6a3e754fa470984f0ae.png
```

**Comment by Omallis** [comment]
Yeah like for some reason it starts with an underscore when downloaded through the client. For example

Danbooru: 
kiso and tenryuu (kantai collection) drawn by orqz - 20fe79072a1928a0bd22d02cc8501532

BooruDownloader: 
__kiso_and_tenryuu_kantai_collection_drawn_by_orqz__20fe79072a1928a0bd22d02cc8501532


is there any way I can get the filename to match Danbooru's?

**Comment by Omallis** [comment]
Ah sorry I see what you mean, I misread. I'll clarify, when you're signed in to Danbooru and you click the download button it properly names the file, but if you download the sample by right clicking and saving as, it will in fact use the underscored naming that showed up for you and me when using the client. 
![untitled2](https://cloud.githubusercontent.com/assets/22080325/18378981/1b0fe576-763e-11e6-90d9-bd3db73f6504.png)

**Comment by Nandaka** [comment]
I'm using their API to fetch the post information.
![image](https://cloud.githubusercontent.com/assets/836867/18379818/04e8993c-76a7-11e6-9a71-b0b714baff2e.png)


If you copy the link from the Download button, the given url actually also have underscores in it. I think it is because the browser for some string replacement in it?

**Comment by Omallis** [comment]
How odd. Yeah I can see now that you mention it, when inspecting it further it is listed with underscores when saved any other way besides clicking the download link. Looking at the inspect element however it is listed with the parenthesis and such before the underscores. I'm not really a coder so I don't know how any of this works. Do you think it's possible to mimic that naming system at all or are the underscores the closest we're going to get?
![untitled2](https://cloud.githubusercontent.com/assets/22080325/18380284/a0fa0a3a-7644-11e6-9edc-f7ce02a568d0.png)

**Comment by Nandaka** [comment]
I don't think I can replicate it to match with the website, as the information is not on the API. 

Performing string replacement ( underscore to space) and trim extra space from the filename doesn't really works. Notice the bracket on kantai collection tag.

Maybe emulate the name format by using
```
%character% (%copyright%) drawn by %artist% - %md5%
```

**Comment by Omallis** [comment]
Thanks man, I tried that out and it's close enough. %character% includes the copyright for whatever reason but it doesn't include the crossover copyrights. So having %copyright% after it ends up double displaying.  Anyways I appreciate you taking the time and helping me. =)
