### ISSUE TITLE
Tags.xml Updated Successfully for e621.net, But Character, Artist and Copyright Tags Don't Work When Naming Files

### ISSUE THREAD

**Issue by Gho57X90** [Nandaka/DanbooruDownloader#85]
In a past issue that has come up, (I'm having trouble relocating issue submission in question), I recall reading that when the tags like _%artist%_, _%character%_ and _%copyright%_ are showing up as 'No Artist', 'No Character' and 'No Copyright', it's because the tags.xml for a provider needs to be updated. I've done this before, having the same issue and it has solved it, but now when I do it for e621.net, it still comes up as 'No Artist' etc.

Is there something I've missed, or is this a new bug?

**Comment by Nandaka** [comment]
can you upload the generated tags.xml? I suspect the contents is empty.

Try to use tags.xml from yande.re

**Comment by Gho57X90** [comment]
Here's the files _tags.xml,_ _tags-e621 (Furry).xml_ and _tags-e621 (Furry).xml.bak_, all last moddified on the 10th of September, 2016.
[Tags XML Files.zip](https://github.com/Nandaka/DanbooruDownloader/files/471468/Tags.XML.Files.zip)

I did check the filels myself, and they came up with the exact same code as each other.
There's also 820 !TMP files for the tags.xml file in the root directory for my install. As I'm not savvy with how the application updates the tags beyond "it downloads them from X site's tags listing via its API", I'm not sure if it's related or not, but I zipped them up as well for your diagnosis if it's of use.
[!TMP tags.xml Files.zip](https://github.com/Nandaka/DanbooruDownloader/files/471464/TMP.tags.xml.Files.zip)

**Comment by Nandaka** [comment]
For some reason, the tags.xml & tags-e621 (Furry).xml only contains single tag definition (mammals, you can check it using notepad). I'm still not sure why, but for time being, delete those files and use tags.xml from yande.re first.

As for the !tmp file, it can be safely deleted.

**Comment by Gho57X90** [comment]
Apologies, but I'm not sure that I understood your instructions clearly.

Did you mean to use the Yande.re tags for e621.net instead, (which to be honest I'm not sure how to configure in that scenario), or did you mean to delete all the tags files and start from scratch with Yande.re first?

**Comment by Nandaka** [comment]
You can just delete both tags.xml first, then download the one from yande.re. No need to update from e621.

**Comment by Gho57X90** [comment]
I deleted the _tags.xml_ and _tags.xml.bak_, and now it only comes up with this.
![2016-09-14_17-48-28](https://cloud.githubusercontent.com/assets/11093715/18504031/7e606c4a-7aa3-11e6-99d1-08c8fa979b21.png)

**Comment by Nandaka** [comment]
weird, it should show the download tags.xml when you run it. Anyway, try to update the tags.xml after restoring it.
