### ISSUE TITLE
Request: filenames setting as %date% tag

### ISSUE THREAD

**Issue by seikun7** [Nandaka/DanbooruDownloader#87]
at ‘Settings – Download – Filename Format’, I want to more add function as %Date% and %Time% (uploaded).

Would you be able to add thie function?

**Comment by Nandaka** [comment]
might be tricky, as each provider have it's own date/time format.
- Danbooru = xml, created_at (2016-09-16T10:40:30-04:00)
- Yande.re = xml, created_at (1475861301 unix timestamp??)
- Gelbooru = xml, created_at (Sun Sep 11 06:53:18 -0500 2016)
- Shimmie = xml/rss, pubDate (Fri, 07 Oct 2016 06:42:02 +0000)
- Sankaku = html, Posted: (@title: 2016-10-07 12:06)
