### ISSUE TITLE
Rating file is not listed.

### ISSUE THREAD

**Issue by 06pori** [Nandaka/DanbooruDownloader#88]
Provider:"rule34hentai.net"
set "Rating: All" ,but the "Contains 3d Loli" rating files can not listed up.
"No 3D Loli" or "Questionable" is OK.

**Comment by Nandaka** [comment]
example?

**Comment by 06pori** [comment]
example Tag : Croix
http://rule34hentai.net/post/view/105348#search=Croix

example Tag : robonepen
http://rule34hentai.net/post/view/185113#search=robonepen

**Comment by Nandaka** [comment]
You need to provide the login information, use the cookie method.

    1. Press F12 on your Chrome browser and select Network tab.
    2. Go to the booru site and login.
    3. Click one of the entry and copy the Cookie value from the Request Header. 
       For gelbooru, it should like this: user_id=<number>; pass_hash=<long string>
       For sankaku, login=<username>; pass_hash=<long string>;
       For shimmie, shm_user=<username>; shm_session=<long string>
    4. Paste the Cookie value to the Username field.
    5. Set Login Type to Cookie. Refer to http://i.imgur.com/rCCjnPs.png

**Comment by 06pori** [comment]
Thank you. I got it.
However, it is not a critical failure, 
When I pressing the "Edit" button and chosed "rule34hentai.net" to Provider ,
"NullReferenceException" error occued, but press Continue then Setting was possible.
