### ISSUE TITLE
Tags download issue (Sankaku Complex)

### ISSUE THREAD

**Issue by Xemnarth** [Nandaka/DanbooruDownloader#89]
Just how many pages of tags do I need to download from SanCom? Mine is currently at page 8483 and still not done yet. In fact it's stuck now and I keep getting Error 429 (too many requests) and it's not going away even after I set a delay for 5-10 seconds between downloads. Can you perhaps share the complete tags.xml from SanCom if you have it downloaded? Thanks!

**Comment by Nandaka** [comment]
Sankaku Tags works by scraping the actual tag page, so you need around 14k++ page. 😈 
![image](https://cloud.githubusercontent.com/assets/836867/19409104/b4636fe4-92ff-11e6-9a49-7f52d5ba32a0.png)

Usually I set the delay to 60s,

Sankaku is blocking a lot of danbooru API, so I have no other choice.

**Comment by Nandaka** [comment]
I've checked my code, I think I've implement code to do tag parsing directly from the sankaku post page,  but you need to change the Settings -> Un-tick “Use Global Tags.xml” 

reference:
https://github.com/Nandaka/DanbooruDownloader/blob/master/DanbooruDownloader3/Engine/SankakuComplexParser.cs#L29
https://github.com/Nandaka/DanbooruDownloader/blob/master/DanbooruDownloader3/FormMain.cs#L312
https://github.com/Nandaka/DanbooruDownloader/blob/master/DanbooruDownloader3/FormMain.Designer.cs#L1933
