### ISSUE TITLE
Option Request-->Download Pools-->yande.re

### ISSUE THREAD

**Issue by EAxp3** [Nandaka/DanbooruDownloader#93]
would be an option to download the pools yande.re

operating mode:
example--> paste the url of the pool in a textbox and download (button-Download)

this option would be very helpful.
please

[pools](https://yande.re/pool)

thanks for your excellent work.

**Comment by Nandaka** [comment]
use search pool:id in the query?

**Comment by EAxp3** [comment]
if it worked, thanks. 👍
