### ISSUE TITLE
Option Request-->change the save folder for each different tag.

### ISSUE THREAD

**Issue by EAxp3** [Nandaka/DanbooruDownloader#94]
![change save folder](https://cloud.githubusercontent.com/assets/15073580/19799592/22cb415c-9cbd-11e6-88fd-dcf8371dc0f7.PNG)

I need this option.
I download many tags and keep them in different folders.
I use --> Full Batch Mode

**Comment by Nandaka** [comment]
use  `%searchtag%` in the filename format, e.g. `%searchtag%\%provider% %id%`
