### ISSUE TITLE
Filter by files extention ?

### ISSUE THREAD

**Issue by yami-no-tusbas** [Nandaka/DanbooruDownloader#95]
Is it possible to add a function to filter saved files by extention, like : "*.jpg, *.png, *.gif, etc" or to exclude somes like : "*.gif, *.webm, etc".

**Comment by Nandaka** [comment]
I think I can add it for Batch Job only

**Comment by keeper8** [comment]
Hi. Could the GUI explain what kind of string should separate multiple file extensions? Thank You.

**Comment by Nandaka** [comment]
It uses Regular Expression to filter out the files. You can use '|' to separate the extensions, for example: `jpg|gif|webm'

https://github.com/Nandaka/DanbooruDownloader/commit/f30598cf8709f570438d748269cecbf02b0c57ee#diff-8c23b2b59b8aa231034b2848a858a643R1089
