### ISSUE TITLE
Bug when adding new entries in Full Batch Mode while it's running

### ISSUE THREAD

**Issue by JMM72** [Nandaka/DanbooruDownloader#97]
Using latest DanbooruDownloader 3.2016.11.12. I was doing some batch downloading to test the new %general% shortcut for the filenames (which works wonderful, really!) when I noticed DD was creating the wrong folders and using the wrong filename format in the weirdest situations.

After a while I realized the pattern followed my own little variations on the filename format for some of the downloads, and finally I was able to reproduce the bug:
1. Add a download with tag 1girl, limit 200, from danbooru, with save folder (filename format) '%searchtag%\\%id%'.
2. Start the batch job.
3. Add a second download with tag 2girls, limit 200, from danbooru, with save folder '%searchtag%\\%md5%'.

The moment you add the second download, the first download will start using the save folder you just introduced for the second download. The provider, limit and search will not be overwritten, but the save folder will be. I don't know if other settings for the download will get overwritten. Again, note this bug only happens while you are already downloading something.

**Comment by JMM72** [comment]
Apparently the bug is more complex than I thought. The save folder gets overwritten in more situations, as my second try at a download of several tags with minor variations in the filename format also ended all of them using the same filename format. I added all the downloads without the batch download running, so it's not only when DD is already downloading.

**Comment by Nandaka** [comment]
Try https://github.com/Nandaka/DanbooruDownloader/releases/tag/v3.20161114

**Comment by JMM72** [comment]
Works fine so far, thanks for the quick fix. And as I said, %general% works very nicely.
