### ISSUE TITLE
Excessive memory consumption with long download lists on Full Batch Mode

### ISSUE THREAD

**Issue by JMM72** [Nandaka/DanbooruDownloader#99]
I'm aware that probably DanbooruDownloader has not been designed with long download lists in mind, since not even the # column can display properly a 3-digit number. However I think you should know its behaviour with them.

I've generated a download list in XML format with 424 elements, downloading from Danbooru one single tag each with a maximum of 100 images (most don't even have 20). In Full Batch Mode, I loaded the list, started batch job and left it there. This morning the computer was totally clogged, all memory consumed, DD didn't respond at all, due to everything having to use virtual memory from swap file. The memory usage was a bit above 7gb.

After cancelling everything and resetting the computer, some investigation told me that I interrupted the jobs in the middle of number 171, but the problems started earlier probably around job number 150.

While this points out at a memory leak or poor list usage, and if PixivDownloader shares code, maybe there too, I'd not say it's a severe bug since I doubt many people would use DD in this way; I did this 424 download for one specific reason and I will probably never repeat the experience. I've divided in chunks of 100 to see if that size is more tolerable, since I think once I did a 80 download list and it worked without problem. I'll post the memory consumption at a 100 download list.

**Comment by Nandaka** [comment]
PixivDownloader uses python, not c#/.net, so no code sharing.

Can you upload the job list here?

**Comment by JMM72** [comment]
For some reason it doesn't allow me to attach it here, although I zipped it. Dowload it from here:
[http://eligeotravez.net/424_jobs_danbooru_limit_100.ZIP](http://eligeotravez.net/424_jobs_danbooru_limit_100.ZIP)

I downloaded a 100 list job with approx. a 5gb memory usage. I forgot to check if 'clear all' brings back the memory.

**Comment by Nandaka** [comment]
Cannot download it from your site, try to upload it to mega/mediafire?

**Comment by Nandaka** [comment]
can you try https://github.com/Nandaka/DanbooruDownloader/releases/tag/v3.20161120 ?

**Comment by JMM72** [comment]
Tried the new 20161120 version.

When I load a batch job XML file, I get the following error from the log:
`[DoBatchJob] Processing Batch Job#0
[DoBatchJob] Downloading list: http://danbooru.donmai.us/post/index.xml?tags=abigail_diaz&limit=200&page=1
[DoBatchJob] Error: La cadena de entrada no tiene el formato correcto.
Stack Trace: 
   en System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   en System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   en System.Convert.ToInt32(String value)
   en DanbooruDownloader3.DAO.DanbooruPostDao.ParsePostAttributes(XmlTextReader reader, DanbooruPost post)
   en DanbooruDownloader3.DAO.DanbooruPostDao.ProcessXML(String rawData)
   en DanbooruDownloader3.DAO.DanbooruPostDao..ctor(Stream input, DanbooruPostDaoOption option)
   en DanbooruDownloader3.FormMain.GetBatchImageList(String url, String query, DanbooruBatchJob job)
   en DanbooruDownloader3.FormMain.DoBatchJob(BindingList`1 batchJob)
Query: abigail_diaz
[DoBatchJob] Downloading list: http://danbooru.donmai.us/post/index.xml?tags=abigail_diaz&limit=200&page=2
[DoBatchJob] No more image.
[DoBatchJob] Batch Job #0: Done`

"La cadena de entrada no tiene el formato correcto" means "The input string doesn't have the right format".

It doesn't matter if I just add one batch job, load a list, etc. It seems to be just an error on calling the  function for string to integer or viceversa.

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/DanbooruDownloader/releases/tag/v3.20161121

**Comment by JMM72** [comment]
Using 20161121. Monitoring the memory while the jobs downloaded, in this one I see a constant memory usage increase, and then memory release, but in the end the memory usage is about the same I'd say, with about 1.5gb for the first 30 jobs.

If you couldn't download my 424 jobs XML, try: [http://www.eligeotravez.net/424_jobs_danbooru_limit_100.ZIP](http://www.eligeotravez.net/424_jobs_danbooru_limit_100.ZIP)

I would reopen the issue.

**Comment by Nandaka** [comment]
>  this one I see a constant memory usage increase, and then memory release, 

Is it the release after everything completed/stopped?

**Comment by JMM72** [comment]
No, there's an increase when each job starts, and a small release after each job completes, then again increase when next job starts. The release doesn't compensate the increase, so maybe there's another memory leak somewhere, other than the one you've fixed.

Last night I was going to report another behaviour but since next time I tried it, it didn't happen, I thought maybe I saw it wrong. But today it happened again. When I press 'Clear Completed' the memory is not released; however when starting the next job, about somewhere in the middle of it, a big part of the memory usage is released *sometimes*. Example: I left some jobs last night, this morning after completion they were taking about 1.4gb memory. I added another job, used 'Clear Completed', and started again. The memory usage increased a bit, and after a while, when it was downloading image 80 of the job or so, I looked again and the memory usage was 300mb, and reduced to 150mb after job completion.

**Comment by Nandaka** [comment]
The GC is handled by OS (even if I trigger GC.Collect(), it will run later).
I tried to do some memory profiling, and by right it should be released after job completion.

**Comment by Nandaka** [comment]
possible fix

http://stackoverflow.com/a/23897411
https://github.com/Nandaka/DanbooruDownloader/blob/master/DanbooruDownloader3/DAO/DanbooruTagsDao.cs#L18

**Comment by JMM72** [comment]
As I've said I don't know C# to follow the subtleties of that text at SO but it sounds good to me. I will test every release you make, specially at my night (Central European Time here). This weekend I was away hence the delay.

**Comment by Nandaka** [comment]
try https://github.com/Nandaka/DanbooruDownloader/releases/tag/v3.20161122

at least it will release the memory after each job completion.

**Comment by JMM72** [comment]
I'm sorry, but the problem persists with 2016.11.22. DD hit the first GB while doing job #21, and the second GB while doing job #43.

**Comment by Nandaka** [comment]
weird, the profiling did release the memory after each job completion.
![image](https://cloud.githubusercontent.com/assets/836867/20498353/d9e73b12-b067-11e6-80bd-e875c68d1f49.png)

I'll try to run it for a while

**Comment by Nandaka** [comment]
running to job 21 using your download list, still around 118MB (and released back to 50+MB on each job completion).

![image](https://cloud.githubusercontent.com/assets/836867/20498988/60281028-b06a-11e6-8bae-d624a38157bf.png)

**Comment by JMM72** [comment]
I just used your executable and Task Manager, nothing fancy. I use Win7 SP1 with all updates. My .NET versions seem to be the same:
```
D:\DVDs\g>dir /b /ad /o-n %systemroot%\Microsoft.NET\Framework\v?.*
v4.0.30319
v3.5
v3.0
v2.0.50727
v1.1.4322
v1.0.3705
```
Have you tried to run the executable outside the debug environment, and just checking the memory usage yourself? There might be a difference between your dev environment and my environment which causes my DD to still not release the memory, but if you'd make that simple test, it would delete a small doubt out of my mind.

Btw with my XML, open it and replace the 100 with 1 so the test runs faster. Don't delete the files after each test, so the next test goes even faster.

**Comment by Nandaka** [comment]
replaced with 1 and it looks OK (50~100MB)
![image](https://cloud.githubusercontent.com/assets/836867/20500218/8da032ba-b06f-11e6-9bf8-ae480a078578.png)
![image](https://cloud.githubusercontent.com/assets/836867/20500291/ce5f9e08-b06f-11e6-9f5f-932417cf078d.png)

**Comment by Nandaka** [comment]
quite stable memory usage 50~100 MB even after 200+job
![image](https://cloud.githubusercontent.com/assets/836867/20500803/f3864a4a-b071-11e6-8604-8fa87b47f0c8.png)

**Comment by Nandaka** [comment]
Try this one, maybe I messed up the upload.
[DanbooruDownloader20161122-beta2.zip](https://github.com/Nandaka/DanbooruDownloader/files/604793/DanbooruDownloader20161122-beta2.zip)

**Comment by JMM72** [comment]
Well then it must be down to my system, you can't fix a bug that you can't reproduce. Thanks for everything tho, I will keep using DD, ofc.

**Comment by Nandaka** [comment]
maybe you can try to run it on different computer and see what happen? something might preventing the GC to run (antivirus?)
